// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

//! Dialect handle, semantic role types, and function catalog types.

use std::sync::Arc;

use syntaqlite_syntax::any::AnyDialect as SyntaxDialect;

#[cfg(feature = "dynload")]
#[expect(clippy::single_component_path_imports)]
use libloading;
pub(crate) use syntaqlite_syntax::util::SqliteVersion;

// ── Semantic role types (re-exported from syntaqlite-common) ─────────────────

pub(crate) use syntaqlite_common::roles::{FIELD_ABSENT, MacroDef, SemanticRole};
#[cfg(test)]
use syntaqlite_common::roles::{FieldIdx, FlagSpec};

// ── Function catalog types ────────────────────────────────────────────────────

/// Category of a built-in function.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum FunctionCategory {
    Scalar,
    Aggregate,
    Window,
    /// Table-valued function — valid in FROM clauses.
    TableValued,
}

/// Whether a cflag enables or omits the function.
///
/// `#[repr(u8)]` with `Enable=0, Omit=1` matches the C ABI
/// (`0=Enable, 1=Omit` in `SyntaqliteAvailabilityRule.cflag_polarity`),
/// which allows [`AvailabilityRule`] to be cast directly from C data.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum CflagPolarity {
    /// Function requires the cflag to be set (`SQLITE_ENABLE`_*).
    Enable = 0,
    /// Function is omitted when the cflag is set (`SQLITE_OMIT`_*).
    Omit = 1,
}

/// Metadata about a built-in function.
#[derive(Debug, Clone, Copy)]
pub(crate) struct FunctionInfo<'a> {
    /// Function name (lowercase).
    pub name: &'a str,
    /// Supported arities. Negative values indicate variadic:
    /// -1 = any number of args, -N = at least N-1 args.
    pub arities: &'a [i16],
    /// Function category.
    pub category: FunctionCategory,
}

/// A version/cflag availability rule for a function.
#[derive(Debug, Clone, Copy)]
pub(crate) struct AvailabilityRule {
    /// Minimum `SQLite` version (inclusive).
    pub since: SqliteVersion,
    /// Maximum `SQLite` version (exclusive). `None` means no upper bound.
    pub until: Option<SqliteVersion>,
    /// Cflag bit index, or `u32::MAX` if no cflag required.
    pub cflag_index: u32,
    /// Polarity of the cflag constraint.
    pub cflag_polarity: CflagPolarity,
}

/// A function entry combining metadata with availability rules.
#[derive(Debug, Clone, Copy)]
pub(crate) struct FunctionEntry<'a> {
    pub info: FunctionInfo<'a>,
    pub availability: &'a [AvailabilityRule],
}

/// Metadata for an always-present built-in relation.
#[derive(Debug, Clone, Copy)]
pub(crate) struct BuiltinRelationInfo<'a> {
    pub name: &'a str,
    pub columns: &'a [&'a str],
    pub without_rowid: bool,
}

/// A built-in relation and the configurations where it exists.
#[derive(Debug, Clone, Copy)]
pub(crate) struct BuiltinRelationEntry<'a> {
    pub info: BuiltinRelationInfo<'a>,
    pub availability: &'a [AvailabilityRule],
}

/// Check whether an availability rule set passes for the dialect config.
///
/// An entry is available if at least one of its availability rules passes.
/// Each rule checks:
/// - version range (`since`/`until`)
/// - cflag constraint: for `Enable` polarity the cflag must be set; for
///   `Omit` polarity the cflag must be clear. Rules with `cflag_index ==
///   u32::MAX` have no cflag constraint.
pub(crate) fn is_available(availability: &[AvailabilityRule], dialect: &AnyDialect) -> bool {
    let cflags = dialect.cflags();
    availability.iter().any(|rule| {
        if dialect.version() < rule.since {
            return false;
        }
        if let Some(until) = rule.until
            && dialect.version() >= until
        {
            return false;
        }
        if rule.cflag_index != u32::MAX {
            let flag_set = cflags.has_index(rule.cflag_index);
            match rule.cflag_polarity {
                CflagPolarity::Enable => {
                    if !flag_set {
                        return false;
                    }
                }
                CflagPolarity::Omit => {
                    if flag_set {
                        return false;
                    }
                }
            }
        }
        true
    })
}

// ── TypedDialect trait ───────────────────────────────────────────────────────

/// Marker trait for typed dialect handles.
///
/// Every dialect has a concrete `Dialect` struct (generated by codegen) that
/// implements this trait and wraps an [`AnyDialect`]. Use the typed handle
/// when you need access to the dialect's typed AST node types (e.g.
/// `nodes::SelectStmt`). When you only need parsing, formatting, or
/// validation, accept [`AnyDialect`] directly -- it is cheaper to clone
/// and works with any dialect.
pub trait TypedDialect: Into<AnyDialect> + Clone + 'static {}

// ── AnyDialect ───────────────────────────────────────────────────────────────

/// Type-erased dialect handle used by the formatter, analyzer, and LSP.
///
/// `AnyDialect` is the common currency type that all syntaqlite infrastructure
/// accepts. It bundles the dialect (parser tables + version/cflag config) with
/// formatter and semantic-role data.
///
/// # Obtaining an `AnyDialect`
///
/// | Method | When to use |
/// |--------|-------------|
/// | [`sqlite_dialect().erase()`](crate::sqlite_dialect) | Built-in `SQLite`, type-erased. |
/// | [`Dialect::new().into()`](crate::Dialect) | Same, via `Into<AnyDialect>`. |
/// | `AnyDialect::load(path, name)` | Dynamically loaded dialect (feature `dynload`). |
///
/// # Example
///
/// ```
/// use syntaqlite::any::AnyDialect;
/// use syntaqlite::util::SqliteVersion;
///
/// // Obtain the built-in SQLite dialect, then configure it.
/// let dialect: AnyDialect = syntaqlite::sqlite_dialect().erase();
/// let dialect = dialect.with_version(SqliteVersion::V3_39);
/// assert_eq!(dialect.version(), SqliteVersion::V3_39);
/// ```
#[derive(Clone)]
pub struct AnyDialect {
    inner: SyntaxDialect,
    /// Pointer to the static `SyntaqliteDialectTemplate` C struct for this dialect.
    /// For built-in dialects this points to a symbol in the binary; for
    /// dynamically loaded dialects the library is kept alive via `_keep_alive`.
    data: *const ffi::CDialectTemplate,
    /// Rust-side cflag set (all 42 flags, u64 bitset). Distinct from the
    /// C-ABI `SqliteSyntaxFlags` stored in the dialect — this covers
    /// non-parser flags like `SQLITE_ENABLE_MATH_FUNCTIONS`.
    ext_cflags: crate::util::SqliteFlags,
    /// Keeps a dynamically loaded library alive for the lifetime of this handle.
    /// `None` for built-in dialects.
    _keep_alive: Option<Arc<dyn Send + Sync>>,
}

// SAFETY: AnyDialect holds a pointer to immutable static C data and an
// Arc-guarded library handle; both are safe to send and share across threads.
unsafe impl Send for AnyDialect {}
// SAFETY: same as Send above.
unsafe impl Sync for AnyDialect {}

impl AnyDialect {
    /// Construct from a pointer to the dialect's static template data.
    ///
    /// Derives the syntax dialect handle from the dialect template,
    /// using default version (latest) and empty cflags.
    ///
    /// # Safety
    ///
    /// `data` must point to a valid [`ffi::CDialectTemplate`] that lives at least as
    /// long as this `AnyDialect` (and all its clones). For built-in dialects
    /// `data` is a `'static` C symbol.
    pub(crate) unsafe fn from_data(data: *const ffi::CDialectTemplate) -> Self {
        // SAFETY: caller guarantees data is valid.
        let inner = unsafe { (*data).syntax_dialect() };
        AnyDialect {
            inner,
            data,
            ext_cflags: crate::util::SqliteFlags::default(),
            _keep_alive: None,
        }
    }

    /// Construct from a [`ffi::CDialect`] value (the C `SyntaqliteDialect`).
    ///
    /// Extracts the template pointer and version/cflags from the C value type,
    /// constructing a dialect handle with the configured version and cflags.
    ///
    /// # Safety
    ///
    /// `dialect.template` must point to a valid [`ffi::CDialectTemplate`] that
    /// lives at least as long as this `AnyDialect` (and all its clones).
    pub(crate) unsafe fn from_c_dialect(dialect: ffi::CDialect) -> Self {
        // SAFETY: caller guarantees dialect.template is valid.
        let mut inner = unsafe { (*dialect.template).syntax_dialect() };
        inner = inner
            .with_version(SqliteVersion::from_int(dialect.sqlite_version))
            .with_cflags(syntaqlite_syntax::util::SqliteSyntaxFlags::from_raw(
                dialect.cflags,
            ));
        AnyDialect {
            inner,
            data: dialect.template,
            ext_cflags: crate::util::SqliteFlags::default(),
            _keep_alive: None,
        }
    }

    /// Return a reference to the static dialect template.
    #[inline]
    fn template(&self) -> &'static ffi::CDialectTemplate {
        // SAFETY: data is valid for 'static (built-in) or kept alive via _keep_alive (dynload).
        unsafe { &*self.data }
    }

    /// The syntax dialect handle for this dialect.
    pub fn syntax_dialect(&self) -> &SyntaxDialect {
        &self.inner
    }

    /// The semantic role table for this dialect, indexed by node tag.
    pub(crate) fn roles(&self) -> &'static [SemanticRole] {
        // SAFETY: template() is valid for the lifetime of self.
        unsafe { self.template().roles() }
    }

    /// The macro definition descriptors for this dialect.
    ///
    /// Each entry describes an AST node type that defines a template macro
    /// (e.g. `CREATE PERFETTO MACRO`). Empty for dialects without macros.
    pub(crate) fn macro_defs(&self) -> &'static [MacroDef] {
        // SAFETY: template() is valid for the lifetime of self.
        unsafe { self.template().macro_defs() }
    }

    /// Whether this dialect has formatter data.
    pub(crate) fn has_fmt_data(&self) -> bool {
        self.template().has_fmt_data()
    }

    /// Read the packed `fmt_dispatch` entry for a node tag.
    pub(crate) fn fmt_dispatch(
        &self,
        tag: syntaqlite_syntax::any::AnyNodeTag,
    ) -> Option<(&[u8], usize)> {
        // SAFETY: template() is valid.
        unsafe { self.template().fmt_dispatch(u32::from(tag) as usize) }
    }

    /// Look up a string from the fmt string table by index (CSR encoding).
    #[inline]
    pub(crate) fn fmt_string(&self, idx: u16) -> &'static str {
        // SAFETY: template() is valid; idx is bounds-checked at codegen time.
        unsafe { self.template().fmt_string(idx as usize) }
    }

    /// Look up a value in the enum display table.
    pub(crate) fn fmt_enum_display_val(&self, idx: usize) -> u16 {
        // SAFETY: template() is valid; idx is bounds-checked at codegen time.
        unsafe { self.template().fmt_enum_display_val(idx) }
    }

    /// Look up `(prec, group)` from the precedence table at `base + ordinal`.
    pub(crate) fn fmt_prec_lookup(&self, base: u16, ordinal: u32) -> (u8, u8) {
        // SAFETY: template() is valid; indices are bounds-checked at codegen time.
        unsafe { self.template().fmt_prec_lookup(base, ordinal) }
    }

    /// Look up the expr-meta for a node tag.
    pub(crate) fn fmt_expr_meta(
        &self,
        tag: syntaqlite_syntax::any::AnyNodeTag,
    ) -> Option<(u8, u16)> {
        // SAFETY: template() is valid.
        unsafe { self.template().fmt_expr_meta(u32::from(tag) as usize) }
    }

    /// Return a copy of this dialect targeting a specific `SQLite` version.
    ///
    /// The version affects which syntax is accepted by the parser and which
    /// built-in functions are available during validation.
    ///
    /// ```
    /// # use syntaqlite::util::SqliteVersion;
    /// let dialect = syntaqlite::sqlite_dialect().erase()
    ///     .with_version(SqliteVersion::V3_35);
    /// assert_eq!(dialect.version(), SqliteVersion::V3_35);
    /// ```
    #[must_use]
    pub fn with_version(mut self, version: SqliteVersion) -> Self {
        self.inner = self.inner.with_version(version);
        self
    }

    /// Return a copy of this dialect with the given compile-time flags.
    ///
    /// Compile-time flags model `SQLITE_ENABLE_*` / `SQLITE_OMIT_*` options.
    /// They control which built-in functions are available during validation.
    ///
    /// ```
    /// use syntaqlite::util::{SqliteFlag, SqliteFlags};
    ///
    /// let dialect = syntaqlite::sqlite_dialect().erase()
    ///     .with_cflags(SqliteFlags::default().with(SqliteFlag::EnableMathFunctions));
    /// assert!(dialect.cflags().has(SqliteFlag::EnableMathFunctions));
    /// ```
    #[must_use]
    pub fn with_cflags(mut self, flags: crate::util::SqliteFlags) -> Self {
        self.ext_cflags = flags;
        self.inner = self.inner.with_cflags(flags.into());
        self
    }

    /// Active compile-time compatibility flags set on this dialect.
    pub fn cflags(&self) -> crate::util::SqliteFlags {
        self.ext_cflags
    }

    /// Target `SQLite` version configured on this dialect.
    pub fn version(&self) -> SqliteVersion {
        self.inner.version()
    }

    /// C-parser compile-time compatibility flags (parser flags, indices 0–21).
    pub fn syntax_cflags(&self) -> syntaqlite_syntax::util::SqliteSyntaxFlags {
        self.inner.cflags()
    }

    /// Construct an [`AnyDialect`] from a pointer returned by a dialect's
    /// `syntaqlite_<name>_dialect()` extern "C" function.
    ///
    /// **This is only intended for external dialect implementations and WASM side-module
    /// loaders.** Normal application code should use [`crate::sqlite_dialect()`] or the
    /// `dynload` feature's `AnyDialect::load` instead.
    ///
    /// # Safety
    ///
    /// `ptr` must point to a valid, fully-initialized [`ffi::CDialectTemplate`] that lives
    /// at least as long as this `AnyDialect` (and all its clones). In practice this is
    /// always a `'static` symbol embedded in a compiled dialect binary.
    pub unsafe fn from_c_dialect_ptr(ptr: *const ffi::CDialectTemplate) -> Self {
        // SAFETY: caller guarantees ptr points to a valid SyntaqliteDialectTemplate.
        unsafe { Self::from_data(ptr) }
    }

    /// Load a dialect from a shared library (`.so` / `.dylib` / `.dll`).
    ///
    /// Resolves the `syntaqlite_<name>_dialect_template` symbol (or
    /// `syntaqlite_dialect_template` when `name` is `None`), which returns a pointer to
    /// a `SyntaqliteDialectTemplate` struct bundling dialect + all data arrays.
    ///
    /// # Errors
    /// Returns `Err` if the library cannot be opened or the dialect symbol is absent.
    ///
    /// Dropping the last clone of the returned handle unloads the library.
    #[cfg(feature = "dynload")]
    pub fn load(path: &str, name: Option<&str>) -> Result<Self, String> {
        // SAFETY: We keep `lib` alive in an `Arc` so the data pointer returned
        // by the dialect symbol lives as long as this `AnyDialect`.
        let lib = unsafe {
            libloading::Library::new(path).map_err(|e| format!("failed to load {path:?}: {e}"))?
        };

        let sym: String = match name {
            Some(n) => format!("syntaqlite_{n}_dialect_template"),
            None => "syntaqlite_dialect_template".to_string(),
        };

        // Resolve the single dialect symbol and call it to get the data pointer.
        // SAFETY: symbol is called immediately; the pointer it returns lives in
        // the library which we keep alive via `keep_alive` below.
        let data: *const ffi::CDialectTemplate = unsafe {
            let func: libloading::Symbol<
                '_,
                unsafe extern "C" fn() -> *const ffi::CDialectTemplate,
            > = lib
                .get(sym.as_bytes())
                .map_err(|e| format!("symbol {sym:?} not found in {path:?}: {e}"))?;
            func()
        };

        // SAFETY: data is valid and kept alive by `keep_alive` below.
        let inner = unsafe { (*data).syntax_dialect() };

        let keep_alive: Arc<dyn Send + Sync> = Arc::new(lib);
        Ok(AnyDialect {
            inner,
            data,
            ext_cflags: crate::util::SqliteFlags::default(),
            _keep_alive: Some(keep_alive),
        })
    }
}

impl std::ops::Deref for AnyDialect {
    type Target = SyntaxDialect;
    fn deref(&self) -> &SyntaxDialect {
        &self.inner
    }
}

impl std::ops::DerefMut for AnyDialect {
    fn deref_mut(&mut self) -> &mut SyntaxDialect {
        &mut self.inner
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[cfg(feature = "sqlite")]
    fn dialect_has_roles() {
        let d = crate::sqlite::dialect::any_dialect();
        assert!(!d.roles().is_empty());
    }

    #[test]
    #[cfg(feature = "sqlite")]
    fn dialect_has_fmt_data() {
        let d = crate::sqlite::dialect::any_dialect();
        assert!(d.has_fmt_data());
    }

    #[test]
    fn semantic_role_variants_exist() {
        let _ = SemanticRole::Transparent;
        let _ = SemanticRole::DefineTable {
            name: 0,
            columns: FIELD_ABSENT,
            select: FIELD_ABSENT,
            without_rowid: FlagSpec::ABSENT,
        };
        let _ = SemanticRole::DefineView {
            name: 0,
            columns: FIELD_ABSENT,
            select: 1,
        };
        let _ = SemanticRole::DefineFunction {
            name: 0,
            args: FIELD_ABSENT,
            return_type: FIELD_ABSENT,
            select: FIELD_ABSENT,
        };
        let _ = SemanticRole::ReturnSpec {
            columns: FIELD_ABSENT,
        };
        let _ = SemanticRole::Import { module: 0 };
    }

    #[test]
    fn field_idx_is_u8() {
        let _: FieldIdx = 42u8;
    }
}

// ── ffi ───────────────────────────────────────────────────────────────────────

/// C-ABI types re-exported from `syntaqlite-syntax`.
pub(crate) mod ffi {
    pub(crate) use syntaqlite_syntax::typed::{CDialect, CDialectTemplate};
}

/// Extension methods on [`ffi::CDialectTemplate`] for fmt/validation access.
///
/// These live here (not in `syntaqlite-syntax`) because they depend on types
/// from `syntaqlite-common` (e.g. [`SemanticRole`]).
pub(crate) trait CDialectTemplateExt {
    /// Construct an [`SyntaxDialect`](syntaqlite_syntax::any::AnyDialect) with
    /// default version and cflags.
    ///
    /// # Safety
    /// `self` must be a valid, fully-initialized `CDialectTemplate`.
    unsafe fn syntax_dialect(&self) -> SyntaxDialect;

    /// The semantic role table for this dialect, indexed by node tag.
    ///
    /// # Safety
    /// `self` must be a valid, fully-initialized `CDialectTemplate`.
    unsafe fn roles(&self) -> &'static [SemanticRole];

    /// The macro definition descriptors for this dialect.
    ///
    /// # Safety
    /// `self` must be a valid, fully-initialized `CDialectTemplate`.
    unsafe fn macro_defs(&self) -> &'static [MacroDef];

    /// Whether this template has formatter data.
    fn has_fmt_data(&self) -> bool;

    /// Read the packed `fmt_dispatch` entry for a node-tag index.
    ///
    /// # Safety
    /// `self` must be a valid, fully-initialized `CDialectTemplate`.
    unsafe fn fmt_dispatch(&self, tag_idx: usize) -> Option<(&[u8], usize)>;

    /// Look up a string from the fmt string table by index (CSR encoding).
    ///
    /// # Safety
    /// `self` must be a valid template and `idx` must be in bounds.
    unsafe fn fmt_string(&self, idx: usize) -> &'static str;

    /// Look up a value in the enum display table.
    ///
    /// # Safety
    /// `self` must be valid and `idx` must be in bounds.
    unsafe fn fmt_enum_display_val(&self, idx: usize) -> u16;

    /// Look up `(prec, group)` from the precedence table at `base + ordinal`.
    ///
    /// # Safety
    /// `self` must be valid and the index must be in bounds.
    unsafe fn fmt_prec_lookup(&self, base: u16, ordinal: u32) -> (u8, u8);

    /// Look up the expr-meta for a node tag.
    ///
    /// # Safety
    /// `self` must be valid and `tag_idx` must be in bounds.
    unsafe fn fmt_expr_meta(&self, tag_idx: usize) -> Option<(u8, u16)>;
}

impl CDialectTemplateExt for ffi::CDialectTemplate {
    unsafe fn syntax_dialect(&self) -> SyntaxDialect {
        // SAFETY: caller guarantees self is valid.
        unsafe { SyntaxDialect::from_dialect_template(std::ptr::from_ref(self)) }
    }

    unsafe fn roles(&self) -> &'static [SemanticRole] {
        // SAFETY: roles_data points to roles_count valid SemanticRole values in static storage.
        unsafe {
            std::slice::from_raw_parts(
                self.roles_data.cast::<SemanticRole>(),
                self.roles_count as usize,
            )
        }
    }

    fn has_fmt_data(&self) -> bool {
        self.fmt_str_count > 0
    }

    unsafe fn macro_defs(&self) -> &'static [MacroDef] {
        // SAFETY: macro_defs_data points to macro_defs_count valid MacroDef values
        // in static storage.
        unsafe {
            std::slice::from_raw_parts(
                self.macro_defs_data.cast::<MacroDef>(),
                self.macro_defs_count as usize,
            )
        }
    }

    unsafe fn fmt_dispatch(&self, tag_idx: usize) -> Option<(&[u8], usize)> {
        if tag_idx >= self.fmt_dispatch_count as usize {
            return None;
        }
        // SAFETY: tag_idx < fmt_dispatch_count; fmt_dispatch is valid for that range.
        let packed = unsafe { *self.fmt_dispatch.add(tag_idx) };
        let offset = (packed >> 16) as u16;
        let length = (packed & 0xFFFF) as u16;
        if offset == 0xFFFF {
            return None;
        }
        let byte_offset = offset as usize * 6;
        let byte_len = length as usize * 6;
        // SAFETY: dispatch entries are bounds-checked at codegen time.
        let slice = unsafe { std::slice::from_raw_parts(self.fmt_ops.add(byte_offset), byte_len) };
        Some((slice, length as usize))
    }

    unsafe fn fmt_string(&self, idx: usize) -> &'static str {
        // SAFETY: offsets has fmt_str_count+1 entries; fmt_str_data covers the range.
        let (start, end) = unsafe {
            (
                *self.fmt_str_offsets.add(idx) as usize,
                *self.fmt_str_offsets.add(idx + 1) as usize,
            )
        };
        // SAFETY: bytes are valid UTF-8 by codegen construction.
        unsafe {
            std::str::from_utf8_unchecked(std::slice::from_raw_parts(
                self.fmt_str_data.add(start),
                end - start,
            ))
        }
    }

    unsafe fn fmt_enum_display_val(&self, idx: usize) -> u16 {
        // SAFETY: callers pass indices checked at codegen time.
        unsafe { *self.fmt_enum_display.add(idx) }
    }

    unsafe fn fmt_prec_lookup(&self, base: u16, ordinal: u32) -> (u8, u8) {
        let idx = base as usize + ordinal as usize;
        let byte_idx = idx * 2;
        // SAFETY: indices are bounds-checked at codegen time.
        let prec = unsafe { *self.fmt_prec_table.add(byte_idx) };
        // SAFETY: byte_idx + 1 is in bounds (prec table has 2 bytes per variant).
        let group = unsafe { *self.fmt_prec_table.add(byte_idx + 1) };
        (prec, group)
    }

    unsafe fn fmt_expr_meta(&self, tag_idx: usize) -> Option<(u8, u16)> {
        if tag_idx >= self.fmt_expr_meta_count as usize {
            return None;
        }
        // SAFETY: tag_idx < fmt_expr_meta_count.
        let packed = unsafe { *self.fmt_expr_meta.add(tag_idx) };
        if packed == 0xFFFF_FFFF {
            return None;
        }
        let op_field_idx = (packed & 0xFF) as u8;
        let prec_table_base = ((packed >> 8) & 0xFFFF) as u16;
        Some((op_field_idx, prec_table_base))
    }
}
