// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.
//
// @generated by syntaqlite-buildtools — DO NOT EDIT

use crate::any::AnyDialect;
use crate::typed::TypedDialect;
use crate::util::{SqliteSyntaxFlags, SqliteVersion};

/// The dialect handle.
///
/// Wraps an [`AnyDialect`] and implements [`TypedDialect`]. Obtain via [`dialect()`];
/// configure with [`with_version`](Self::with_version) and [`with_cflags`](Self::with_cflags).
#[derive(Clone)]
pub struct Dialect {
    raw: AnyDialect,
}

impl Dialect {
    /// Return the underlying [`AnyDialect`] by value.
    pub fn into_raw(self) -> AnyDialect {
        self.raw
    }

    /// Construct from a raw [`AnyDialect`].
    ///
    /// Used by dialect loading infrastructure to build a typed dialect handle
    /// from the dialect embedded in a `CDialectTemplate`.
    pub fn from_raw(raw: AnyDialect) -> Self {
        Self { raw }
    }

    /// Set the target `SQLite` version.
    #[must_use]
    pub fn with_version(mut self, version: SqliteVersion) -> Self {
        self.raw = self.raw.with_version(version);
        self
    }

    /// Replace the entire cflags bitfield.
    #[must_use]
    pub fn with_cflags(mut self, cflags: SqliteSyntaxFlags) -> Self {
        self.raw = self.raw.with_cflags(cflags);
        self
    }
}

impl From<Dialect> for AnyDialect {
    fn from(g: Dialect) -> AnyDialect {
        g.raw
    }
}

impl TypedDialect for Dialect {
    type Node<'a> = super::ast::Stmt<'a>;
    type NodeId = super::ast::NodeId;
    type Token = super::tokens::TokenType;
}

/// Returns the dialect handle.
pub fn dialect() -> Dialect {
    // SAFETY: syntaqlite_sqlite_dialect() returns a valid static C dialect descriptor.
    let raw = unsafe { AnyDialect::new(ffi::syntaqlite_sqlite_dialect()) };
    Dialect { raw }
}

// ── ffi ───────────────────────────────────────────────────────────────────────

mod ffi {
    unsafe extern "C" {
        pub(super) fn syntaqlite_sqlite_dialect() -> crate::typed::CDialect;
    }
}
