// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.
//
// @generated by syntaqlite-buildtools — DO NOT EDIT

#include "syntaqlite/dialect.h"
#include "csrc/sqlite/dialect_fmt.h"
#include "csrc/sqlite/dialect_meta.h"
#include "csrc/sqlite/dialect_roles.h"
#include "csrc/sqlite/dialect_tokens.h"
#include "csrc/sqlite/sqlite_parse.h"
#include "csrc/sqlite/sqlite_tokenize.h"
#include "syntaqlite_sqlite/sqlite_tokens.h"

extern const char synq_sqlite_zKWText[];
extern const unsigned short int synq_sqlite_aKWOffset[];
extern const unsigned char synq_sqlite_aKWLen[];
extern const unsigned char synq_sqlite_aKWCode[];
extern const unsigned int synq_sqlite_nKeyword;

// ============ sqlite dialect descriptor ============

static const SyntaqliteDialectTemplate SQLITE_DIALECT = {
    .name = "sqlite",

    // AST metadata
    .node_count = sizeof(ast_meta_node_names) / sizeof(ast_meta_node_names[0]),
    .node_names = ast_meta_node_names,
    .field_meta = ast_meta_field_meta,
    .field_meta_counts = ast_meta_field_meta_counts,
    .list_tags = ast_meta_list_tags,
    .range_meta = ast_meta_range_meta,

    // Parser lifecycle
    .parser_alloc = SynqSqliteParseAlloc,
    .parser_init = SynqSqliteParseInit,
    .parser_finalize = SynqSqliteParseFinalize,
    .parser_free = SynqSqliteParseFree,
    .parser_feed = SynqSqliteParse,
#ifndef NDEBUG
    .parser_trace = SynqSqliteParseTrace,
#endif
    .parser_expected_tokens = SynqSqliteParseExpectedTokens,
    .parser_completion_context = SynqSqliteParseCompletionContext,

    // Tokenizer
    .get_token = SynqSqliteGetToken,

    // Keyword table
    .keyword_text = synq_sqlite_zKWText,
    .keyword_offsets = synq_sqlite_aKWOffset,
    .keyword_lens = synq_sqlite_aKWLen,
    .keyword_codes = synq_sqlite_aKWCode,
    .keyword_count = &synq_sqlite_nKeyword,

    // Token metadata
    .token_categories = token_categories,
    .token_type_count = TOKEN_TYPE_COUNT,
    .macro_style = SYNQ_MACRO_STYLE_NONE,

    .fmt_str_data = sqlite_fmt_string_data,
    .fmt_str_offsets = sqlite_fmt_string_offsets,
    .fmt_str_count = sqlite_fmt_string_count,
    .fmt_enum_display = sqlite_fmt_enum_display,
    .fmt_enum_display_count = sqlite_fmt_enum_display_count,
    .fmt_ops = sqlite_fmt_ops,
    .fmt_ops_count = sqlite_fmt_ops_count,
    .fmt_dispatch = sqlite_fmt_dispatch,
    .fmt_dispatch_count = sqlite_fmt_dispatch_count,
    .fmt_prec_table = sqlite_fmt_prec_table,
    .fmt_prec_table_count = sqlite_fmt_prec_table_count,
    .fmt_expr_meta = sqlite_fmt_expr_meta,
    .fmt_expr_meta_count = sqlite_fmt_expr_meta_count,
    .roles_data = sqlite_roles_data,
    .roles_count = sqlite_roles_count,
    .macro_defs_data = sqlite_macro_defs_data,
    .macro_defs_count = sqlite_macro_defs_count,
};

SYNTAQLITE_API SyntaqliteDialect syntaqlite_sqlite_dialect(void) {
  return (SyntaqliteDialect)SYNQ_DIALECT_DEFAULT(&SQLITE_DIALECT);
}
