// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.
//
// @generated by syntaqlite-buildtools — DO NOT EDIT

#ifndef SYNTAQLITE_SQLITE_PARSE_H
#define SYNTAQLITE_SQLITE_PARSE_H

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#include "syntaqlite_dialect/ast_builder.h"
#include "syntaqlite_dialect/dialect_abi.h"

#ifdef __cplusplus
extern "C" {
#endif

SYNTAQLITE_DIALECT_API void* SynqSqliteParseAlloc(void* (*mallocProc)(size_t),
                                                  SynqParseCtx* pCtx);
SYNTAQLITE_DIALECT_API void SynqSqliteParseInit(void* parser,
                                                SynqParseCtx* pCtx);
SYNTAQLITE_DIALECT_API void SynqSqliteParseFinalize(void* parser);
SYNTAQLITE_DIALECT_API void SynqSqliteParseFree(void* parser,
                                                void (*freeProc)(void*));
SYNTAQLITE_DIALECT_API void SynqSqliteParse(void* parser,
                                            int token_type,
                                            SynqParseToken minor);
SYNTAQLITE_DIALECT_API uint32_t
SynqSqliteParseExpectedTokens(void* parser,
                              uint32_t* out_tokens,
                              uint32_t out_cap);
SYNTAQLITE_DIALECT_API uint32_t SynqSqliteParseCompletionContext(void* parser);
SYNTAQLITE_DIALECT_API int SynqSqliteParseFallback(int iToken);
#ifndef NDEBUG
SYNTAQLITE_DIALECT_API void SynqSqliteParseTrace(FILE* trace_file,
                                                 char* prompt);
#endif

#ifdef __cplusplus
}
#endif

#endif  // SYNTAQLITE_SQLITE_PARSE_H
