# Copyright 2025 The syntaqlite Authors. All rights reserved.
# Licensed under the Apache License, Version 2.0.

"""Centralized constants for SQLite extraction.

This module contains magic strings, markers, and symbol names used
throughout the extraction process. Centralizing them here ensures
consistency and makes updates easier when upstream SQLite changes.
"""

# ==============================================================================
# Lemon-generated Section Markers
# ==============================================================================

# Token definitions section
TOKEN_DEFS_START = "/* These constants specify the various numeric values for terminal symbols."
TOKEN_DEFS_END = "/**************** End token definitions ***************************************/"

# Control #defines section
CONTROL_DEFS_START = "/************* Begin control #defines *****************************************/"
CONTROL_DEFS_END = "/************* End control #defines *******************************************/"

# Parsing tables section
PARSING_TABLES_START = "/*********** Begin parsing tables **********************************************/"
PARSING_TABLES_END = "/********** End of lemon-generated parsing tables *****************************/"

# Reduce actions section
REDUCE_ACTIONS_START = "/********** Begin reduce actions **********************************************/"
REDUCE_ACTIONS_END = "/********** End reduce actions ************************************************/"

# ==============================================================================
# Array Declaration Patterns
# ==============================================================================

FALLBACK_ARRAY_DECL = "static const YYCODETYPE yyFallback[] = {"
TOKEN_NAMES_ARRAY_DECL = "static const char *const yyTokenName[] = {"
RULE_NAMES_ARRAY_DECL = "static const char *const yyRuleName[] = {"
RULE_INFO_LHS_ARRAY_DECL = "static const YYCODETYPE yyRuleInfoLhs[] = {"
RULE_INFO_NRHS_ARRAY_DECL = "static const signed char yyRuleInfoNRhs[] = {"

# ==============================================================================
# Preprocessor Guards and Macros
# ==============================================================================

# Guard for external parser data injection
EXTERNAL_PARSER_GUARD = "_SYNTAQLITE_EXTERNAL_PARSER"

# Macro name for parser data file inclusion
PARSER_DATA_FILE_MACRO = "SYNTAQLITE_PARSER_DATA_FILE"

# Guard for external keywordhash data injection
EXTERNAL_KEYWORDHASH_GUARD = "_SYNTAQLITE_EXTERNAL_KEYWORDHASH"

# Macro name for keywordhash data file inclusion
KEYWORDHASH_DATA_FILE_MACRO = "SYNTAQLITE_KEYWORDHASH_DATA_FILE"

# ==============================================================================
# Conditional Compilation Markers
# ==============================================================================

YYFALLBACK_IFDEF = "#ifdef YYFALLBACK"
YYCOVERAGE_NDEBUG_IFDEF = "#if defined(YYCOVERAGE) || !defined(NDEBUG)"
NDEBUG_IFNDEF = "#ifndef NDEBUG"

# ==============================================================================
# Keywordhash Processing
# ==============================================================================

# Marker at start of generated keywordhash content
KEYWORDHASH_SCORE_MARKER = "/* Hash score:"

# Marker for keywordCode function
KEYWORD_CODE_FUNC_MARKER = "static int keywordCode("

# Keywordhash array symbols that need renaming
KEYWORDHASH_ARRAY_SYMBOLS = [
    "zKWText",
    "aKWHash",
    "aKWNext",
    "aKWLen",
    "aKWOffset",
    "aKWCode",
]

# ==============================================================================
# Parser Symbol Names (Lemon-generated)
# ==============================================================================

# Public API symbols generated by Lemon that need renaming
LEMON_PUBLIC_SYMBOLS = [
    "Parse",
    "ParseAlloc",
    "ParseFree",
    "ParseInit",
    "ParseFinalize",
    "ParseTrace",
    "ParseFallback",
    "ParseCoverage",
    "ParseStackPeak",
]

# Internal parser symbols that need renaming to avoid conflicts
LEMON_INTERNAL_SYMBOLS = [
    "yyParser",
    "yyStackEntry",
]
