// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.
//
// @generated by syntaqlite-buildtools — DO NOT EDIT

#ifndef SYNTAQLITE_SQLITE_GRAMMAR_H
#define SYNTAQLITE_SQLITE_GRAMMAR_H

#include "syntaqlite/dialect.h"
#include "syntaqlite/parser.h"
#include "syntaqlite/tokenizer.h"

#ifdef __cplusplus
extern "C" {
#endif

SYNTAQLITE_API SyntaqliteDialect syntaqlite_sqlite_dialect(void);
SYNTAQLITE_API const SyntaqliteDialectTemplate*
syntaqlite_sqlite_dialect_template(void);

SYNTAQLITE_API SyntaqliteParser* syntaqlite_parser_create_sqlite(
    const SyntaqliteMemMethods* mem);
SYNTAQLITE_API SyntaqliteTokenizer* syntaqlite_tokenizer_create_sqlite(
    const SyntaqliteMemMethods* mem);

#ifdef __cplusplus
}
#endif

#endif  // SYNTAQLITE_SQLITE_GRAMMAR_H
