// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.
//
// @generated by syntaqlite-buildtools — DO NOT EDIT

#ifndef SYNTAQLITE_SQLITE_GRAMMAR_H
#define SYNTAQLITE_SQLITE_GRAMMAR_H

#include "syntaqlite/dialect.h"

#ifdef __cplusplus
extern "C" {
#endif

SYNTAQLITE_API SyntaqliteDialect syntaqlite_sqlite_dialect(void);
SYNTAQLITE_API const SyntaqliteDialectTemplate*
syntaqlite_sqlite_dialect_template(void);

#ifdef __cplusplus
}
#endif

#endif  // SYNTAQLITE_SQLITE_GRAMMAR_H
