// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

// Generated from ast_codegen node definitions - DO NOT EDIT
// Regenerate with: python3 python/tools/extract_sqlite.py

#include "src/formatter/fmt_ops.h"

#include "src/parser/ast_nodes_gen.h"

// ============ Format Recipes ============

static const SynqFmtEnumEntry fmt_binary_expr_entries_1[] = {
    { SYNQ_BINARY_OP_PLUS, "+" },
    { SYNQ_BINARY_OP_MINUS, "-" },
    { SYNQ_BINARY_OP_STAR, "*" },
    { SYNQ_BINARY_OP_SLASH, "/" },
    { SYNQ_BINARY_OP_REM, "%" },
    { SYNQ_BINARY_OP_LT, "<" },
    { SYNQ_BINARY_OP_GT, ">" },
    { SYNQ_BINARY_OP_LE, "<=" },
    { SYNQ_BINARY_OP_GE, ">=" },
    { SYNQ_BINARY_OP_EQ, "=" },
    { SYNQ_BINARY_OP_NE, "!=" },
    { SYNQ_BINARY_OP_AND, "AND" },
    { SYNQ_BINARY_OP_OR, "OR" },
    { SYNQ_BINARY_OP_BITAND, "&" },
    { SYNQ_BINARY_OP_BITOR, "|" },
    { SYNQ_BINARY_OP_LSHIFT, "<<" },
    { SYNQ_BINARY_OP_RSHIFT, ">>" },
    { SYNQ_BINARY_OP_CONCAT, "||" },
    { SYNQ_BINARY_OP_PTR, "->" },
};

static const SynqFmtOp fmt_binary_expr[] = {
    FOP_SWITCH_DEFAULT(BinaryExpr, op, 2),
    FOP_CASE(SYNQ_BINARY_OP_AND),
    FOP_SEQ(4),
    FOP_CHILD(BinaryExpr, left),
    FOP_LINE,
    FOP_KW("AND "),
    FOP_CHILD(BinaryExpr, right),
    FOP_CASE(SYNQ_BINARY_OP_OR),
    FOP_SEQ(4),
    FOP_CHILD(BinaryExpr, left),
    FOP_LINE,
    FOP_KW("OR "),
    FOP_CHILD(BinaryExpr, right),
    FOP_GROUP,
    FOP_SEQ(5),
    FOP_CHILD(BinaryExpr, left),
    FOP_LINE,
    FOP_ENUM_DISPLAY(BinaryExpr, op, fmt_binary_expr_entries_1, 19),
    FOP_KW(" "),
    FOP_CHILD(BinaryExpr, right),
};

static const SynqFmtEnumEntry fmt_unary_expr_entries_1[] = {
    { SYNQ_UNARY_OP_MINUS, "-" },
    { SYNQ_UNARY_OP_PLUS, "+" },
    { SYNQ_UNARY_OP_BITNOT, "~" },
    { SYNQ_UNARY_OP_NOT, "NOT " },
};

static const SynqFmtOp fmt_unary_expr[] = {
    FOP_SEQ(2),
    FOP_ENUM_DISPLAY(UnaryExpr, op, fmt_unary_expr_entries_1, 4),
    FOP_CHILD(UnaryExpr, operand),
};

static const SynqFmtOp fmt_literal[] = {
    FOP_SPAN(Literal, source),
};

static const SynqFmtOp fmt_result_column[] = {
    FOP_SEQ(2),
    FOP_IF_FLAG_ELSE(ResultColumn, flags, 0x01),
    FOP_IF_SET_ELSE(ResultColumn, expr),
    FOP_SEQ(2),
    FOP_CHILD(ResultColumn, expr),
    FOP_KW(".*"),
    FOP_KW("*"),
    FOP_CHILD(ResultColumn, expr),
    FOP_IF_SPAN(ResultColumn, alias),
    FOP_SEQ(2),
    FOP_KW(" AS "),
    FOP_SPAN(ResultColumn, alias),
};

static const SynqFmtOp fmt_select_stmt[] = {
    FOP_GROUP,
    FOP_SEQ(9),
    FOP_IF_FLAG_ELSE(SelectStmt, flags, 0x01),
    FOP_KW("SELECT DISTINCT"),
    FOP_KW("SELECT"),
    FOP_IF_SET(SelectStmt, columns),
    FOP_GROUP,
    FOP_NEST,
    FOP_SEQ(2),
    FOP_LINE,
    FOP_CHILD(SelectStmt, columns),
    FOP_CLAUSE(SelectStmt, from_clause, "FROM"),
    FOP_CLAUSE(SelectStmt, where, "WHERE"),
    FOP_CLAUSE(SelectStmt, groupby, "GROUP BY"),
    FOP_CLAUSE(SelectStmt, having, "HAVING"),
    FOP_CLAUSE(SelectStmt, orderby, "ORDER BY"),
    FOP_CLAUSE(SelectStmt, limit_clause, "LIMIT"),
    FOP_CLAUSE(SelectStmt, window_clause, "WINDOW"),
};

static const SynqFmtOp fmt_ordering_term[] = {
    FOP_SEQ(4),
    FOP_CHILD(OrderingTerm, expr),
    FOP_IF_ENUM(OrderingTerm, sort_order, SYNQ_SORT_ORDER_DESC),
    FOP_KW(" DESC"),
    FOP_IF_ENUM(OrderingTerm, nulls_order, SYNQ_NULLS_ORDER_FIRST),
    FOP_KW(" NULLS FIRST"),
    FOP_IF_ENUM(OrderingTerm, nulls_order, SYNQ_NULLS_ORDER_LAST),
    FOP_KW(" NULLS LAST"),
};

static const SynqFmtOp fmt_limit_clause[] = {
    FOP_SEQ(2),
    FOP_CHILD(LimitClause, limit),
    FOP_IF_SET(LimitClause, offset),
    FOP_SEQ(2),
    FOP_KW(" OFFSET "),
    FOP_CHILD(LimitClause, offset),
};

static const SynqFmtOp fmt_column_ref[] = {
    FOP_SEQ(3),
    FOP_IF_SPAN(ColumnRef, schema),
    FOP_SEQ(2),
    FOP_SPAN(ColumnRef, schema),
    FOP_KW("."),
    FOP_IF_SPAN(ColumnRef, table),
    FOP_SEQ(2),
    FOP_SPAN(ColumnRef, table),
    FOP_KW("."),
    FOP_SPAN(ColumnRef, column),
};

static const SynqFmtOp fmt_function_call[] = {
    FOP_SEQ(4),
    FOP_SPAN(FunctionCall, func_name),
    FOP_GROUP,
    FOP_SEQ(5),
    FOP_KW("("),
    FOP_IF_FLAG(FunctionCall, flags, 0x01),
    FOP_KW("DISTINCT "),
    FOP_IF_FLAG_ELSE(FunctionCall, flags, 0x02),
    FOP_KW("*"),
    FOP_IF_SET(FunctionCall, args),
    FOP_NEST,
    FOP_SEQ(2),
    FOP_SOFTLINE,
    FOP_CHILD(FunctionCall, args),
    FOP_SOFTLINE,
    FOP_KW(")"),
    FOP_IF_SET(FunctionCall, filter_clause),
    FOP_SEQ(3),
    FOP_KW(" FILTER (WHERE "),
    FOP_CHILD(FunctionCall, filter_clause),
    FOP_KW(")"),
    FOP_IF_SET(FunctionCall, over_clause),
    FOP_SEQ(2),
    FOP_KW(" OVER "),
    FOP_CHILD(FunctionCall, over_clause),
};

static const SynqFmtOp fmt_is_expr[] = {
    FOP_SWITCH(IsExpr, op, 6),
    FOP_CASE(SYNQ_IS_OP_ISNULL),
    FOP_SEQ(2),
    FOP_CHILD(IsExpr, left),
    FOP_KW(" ISNULL"),
    FOP_CASE(SYNQ_IS_OP_NOTNULL),
    FOP_SEQ(2),
    FOP_CHILD(IsExpr, left),
    FOP_KW(" NOTNULL"),
    FOP_CASE(SYNQ_IS_OP_IS),
    FOP_SEQ(3),
    FOP_CHILD(IsExpr, left),
    FOP_KW(" IS "),
    FOP_CHILD(IsExpr, right),
    FOP_CASE(SYNQ_IS_OP_IS_NOT),
    FOP_SEQ(3),
    FOP_CHILD(IsExpr, left),
    FOP_KW(" IS NOT "),
    FOP_CHILD(IsExpr, right),
    FOP_CASE(SYNQ_IS_OP_IS_NOT_DISTINCT),
    FOP_SEQ(3),
    FOP_CHILD(IsExpr, left),
    FOP_KW(" IS NOT DISTINCT FROM "),
    FOP_CHILD(IsExpr, right),
    FOP_CASE(SYNQ_IS_OP_IS_DISTINCT),
    FOP_SEQ(3),
    FOP_CHILD(IsExpr, left),
    FOP_KW(" IS DISTINCT FROM "),
    FOP_CHILD(IsExpr, right),
};

static const SynqFmtOp fmt_between_expr[] = {
    FOP_SEQ(5),
    FOP_CHILD(BetweenExpr, operand),
    FOP_IF_ENUM_ELSE(BetweenExpr, negated, SYNQ_BOOL_TRUE),
    FOP_KW(" NOT BETWEEN "),
    FOP_KW(" BETWEEN "),
    FOP_CHILD(BetweenExpr, low),
    FOP_KW(" AND "),
    FOP_CHILD(BetweenExpr, high),
};

static const SynqFmtOp fmt_like_expr[] = {
    FOP_SEQ(4),
    FOP_CHILD(LikeExpr, operand),
    FOP_IF_ENUM_ELSE(LikeExpr, negated, SYNQ_BOOL_TRUE),
    FOP_KW(" NOT LIKE "),
    FOP_KW(" LIKE "),
    FOP_CHILD(LikeExpr, pattern),
    FOP_IF_SET(LikeExpr, escape),
    FOP_SEQ(2),
    FOP_KW(" ESCAPE "),
    FOP_CHILD(LikeExpr, escape),
};

static const SynqFmtOp fmt_case_expr[] = {
    FOP_SEQ(5),
    FOP_KW("CASE"),
    FOP_IF_SET(CaseExpr, operand),
    FOP_SEQ(2),
    FOP_KW(" "),
    FOP_CHILD(CaseExpr, operand),
    FOP_CHILD(CaseExpr, whens),
    FOP_IF_SET(CaseExpr, else_expr),
    FOP_SEQ(2),
    FOP_KW(" ELSE "),
    FOP_CHILD(CaseExpr, else_expr),
    FOP_KW(" END"),
};

static const SynqFmtOp fmt_case_when[] = {
    FOP_SEQ(4),
    FOP_KW(" WHEN "),
    FOP_CHILD(CaseWhen, when_expr),
    FOP_KW(" THEN "),
    FOP_CHILD(CaseWhen, then_expr),
};

static const SynqFmtOp fmt_case_when_list[] = {
    FOP_FOR_EACH,
    FOP_CHILD_ITEM,
};

static const SynqFmtEnumEntry fmt_compound_select_entries_1[] = {
    { SYNQ_COMPOUND_OP_UNION, "UNION" },
    { SYNQ_COMPOUND_OP_UNION_ALL, "UNION ALL" },
    { SYNQ_COMPOUND_OP_INTERSECT, "INTERSECT" },
    { SYNQ_COMPOUND_OP_EXCEPT, "EXCEPT" },
};

static const SynqFmtOp fmt_compound_select[] = {
    FOP_SEQ(5),
    FOP_CHILD(CompoundSelect, left),
    FOP_HARDLINE,
    FOP_ENUM_DISPLAY(CompoundSelect, op, fmt_compound_select_entries_1, 4),
    FOP_HARDLINE,
    FOP_CHILD(CompoundSelect, right),
};

static const SynqFmtOp fmt_subquery_expr[] = {
    FOP_SEQ(3),
    FOP_KW("("),
    FOP_CHILD(SubqueryExpr, select),
    FOP_KW(")"),
};

static const SynqFmtOp fmt_exists_expr[] = {
    FOP_SEQ(3),
    FOP_KW("EXISTS ("),
    FOP_CHILD(ExistsExpr, select),
    FOP_KW(")"),
};

static const SynqFmtOp fmt_in_expr[] = {
    FOP_SEQ(5),
    FOP_CHILD(InExpr, operand),
    FOP_IF_ENUM_ELSE(InExpr, negated, SYNQ_BOOL_TRUE),
    FOP_KW(" NOT IN "),
    FOP_KW(" IN "),
    FOP_KW("("),
    FOP_CHILD(InExpr, source),
    FOP_KW(")"),
};

static const SynqFmtOp fmt_variable[] = {
    FOP_SPAN(Variable, source),
};

static const SynqFmtOp fmt_collate_expr[] = {
    FOP_SEQ(3),
    FOP_CHILD(CollateExpr, expr),
    FOP_KW(" COLLATE "),
    FOP_SPAN(CollateExpr, collation),
};

static const SynqFmtOp fmt_cast_expr[] = {
    FOP_SEQ(5),
    FOP_KW("CAST("),
    FOP_CHILD(CastExpr, expr),
    FOP_KW(" AS "),
    FOP_SPAN(CastExpr, type_name),
    FOP_KW(")"),
};

static const SynqFmtOp fmt_values_row_list[] = {
    FOP_FOR_EACH_SEP,
    FOP_SEQ(3),
    FOP_KW("("),
    FOP_CHILD_ITEM,
    FOP_KW(")"),
    FOP_SEQ(2),
    FOP_KW(","),
    FOP_LINE,
};

static const SynqFmtOp fmt_values_clause[] = {
    FOP_SEQ(2),
    FOP_KW("VALUES"),
    FOP_NEST,
    FOP_SEQ(2),
    FOP_HARDLINE,
    FOP_CHILD(ValuesClause, rows),
};

static const SynqFmtOp fmt_cte_definition[] = {
    FOP_SEQ(8),
    FOP_SPAN(CteDefinition, cte_name),
    FOP_IF_SET(CteDefinition, columns),
    FOP_SEQ(3),
    FOP_KW("("),
    FOP_CHILD(CteDefinition, columns),
    FOP_KW(")"),
    FOP_KW(" AS "),
    FOP_IF_ENUM(CteDefinition, materialized, SYNQ_MATERIALIZED_MATERIALIZED),
    FOP_KW("MATERIALIZED "),
    FOP_IF_ENUM(CteDefinition, materialized, SYNQ_MATERIALIZED_NOT_MATERIALIZED),
    FOP_KW("NOT MATERIALIZED "),
    FOP_KW("("),
    FOP_CHILD(CteDefinition, select),
    FOP_KW(")"),
};

static const SynqFmtOp fmt_with_clause[] = {
    FOP_SEQ(4),
    FOP_IF_ENUM_ELSE(WithClause, recursive, SYNQ_BOOL_TRUE),
    FOP_KW("WITH RECURSIVE "),
    FOP_KW("WITH "),
    FOP_CHILD(WithClause, ctes),
    FOP_HARDLINE,
    FOP_CHILD(WithClause, select),
};

static const SynqFmtOp fmt_aggregate_function_call[] = {
    FOP_SEQ(4),
    FOP_SPAN(AggregateFunctionCall, func_name),
    FOP_GROUP,
    FOP_SEQ(6),
    FOP_KW("("),
    FOP_IF_FLAG(AggregateFunctionCall, flags, 0x01),
    FOP_KW("DISTINCT "),
    FOP_IF_SET(AggregateFunctionCall, args),
    FOP_NEST,
    FOP_SEQ(2),
    FOP_SOFTLINE,
    FOP_CHILD(AggregateFunctionCall, args),
    FOP_IF_SET(AggregateFunctionCall, orderby),
    FOP_SEQ(2),
    FOP_KW(" ORDER BY "),
    FOP_CHILD(AggregateFunctionCall, orderby),
    FOP_SOFTLINE,
    FOP_KW(")"),
    FOP_IF_SET(AggregateFunctionCall, filter_clause),
    FOP_SEQ(3),
    FOP_KW(" FILTER (WHERE "),
    FOP_CHILD(AggregateFunctionCall, filter_clause),
    FOP_KW(")"),
    FOP_IF_SET(AggregateFunctionCall, over_clause),
    FOP_SEQ(2),
    FOP_KW(" OVER "),
    FOP_CHILD(AggregateFunctionCall, over_clause),
};

static const SynqFmtOp fmt_raise_expr[] = {
    FOP_SEQ(4),
    FOP_KW("RAISE("),
    FOP_SWITCH(RaiseExpr, raise_type, 4),
    FOP_CASE(SYNQ_RAISE_TYPE_IGNORE),
    FOP_KW("IGNORE"),
    FOP_CASE(SYNQ_RAISE_TYPE_ROLLBACK),
    FOP_KW("ROLLBACK"),
    FOP_CASE(SYNQ_RAISE_TYPE_ABORT),
    FOP_KW("ABORT"),
    FOP_CASE(SYNQ_RAISE_TYPE_FAIL),
    FOP_KW("FAIL"),
    FOP_IF_SET(RaiseExpr, error_message),
    FOP_SEQ(2),
    FOP_KW(", "),
    FOP_CHILD(RaiseExpr, error_message),
    FOP_KW(")"),
};

static const SynqFmtOp fmt_table_ref[] = {
    FOP_SEQ(3),
    FOP_IF_SPAN(TableRef, schema),
    FOP_SEQ(2),
    FOP_SPAN(TableRef, schema),
    FOP_KW("."),
    FOP_SPAN(TableRef, table_name),
    FOP_IF_SPAN(TableRef, alias),
    FOP_SEQ(2),
    FOP_KW(" AS "),
    FOP_SPAN(TableRef, alias),
};

static const SynqFmtOp fmt_subquery_table_source[] = {
    FOP_SEQ(4),
    FOP_KW("("),
    FOP_CHILD(SubqueryTableSource, select),
    FOP_KW(")"),
    FOP_IF_SPAN(SubqueryTableSource, alias),
    FOP_SEQ(2),
    FOP_KW(" AS "),
    FOP_SPAN(SubqueryTableSource, alias),
};

static const SynqFmtEnumEntry fmt_join_clause_entries_1[] = {
    { SYNQ_JOIN_TYPE_INNER, "JOIN" },
    { SYNQ_JOIN_TYPE_LEFT, "LEFT JOIN" },
    { SYNQ_JOIN_TYPE_RIGHT, "RIGHT JOIN" },
    { SYNQ_JOIN_TYPE_FULL, "FULL JOIN" },
    { SYNQ_JOIN_TYPE_CROSS, "CROSS JOIN" },
    { SYNQ_JOIN_TYPE_NATURAL_INNER, "NATURAL JOIN" },
    { SYNQ_JOIN_TYPE_NATURAL_LEFT, "NATURAL LEFT JOIN" },
    { SYNQ_JOIN_TYPE_NATURAL_RIGHT, "NATURAL RIGHT JOIN" },
    { SYNQ_JOIN_TYPE_NATURAL_FULL, "NATURAL FULL JOIN" },
    { SYNQ_JOIN_TYPE_COMMA, "," },
};

static const SynqFmtOp fmt_join_clause[] = {
    FOP_SWITCH_DEFAULT(JoinClause, join_type, 1),
    FOP_CASE(SYNQ_JOIN_TYPE_COMMA),
    FOP_SEQ(5),
    FOP_CHILD(JoinClause, left),
    FOP_KW(", "),
    FOP_CHILD(JoinClause, right),
    FOP_IF_SET(JoinClause, on_expr),
    FOP_SEQ(3),
    FOP_HARDLINE,
    FOP_KW("ON "),
    FOP_CHILD(JoinClause, on_expr),
    FOP_IF_SET(JoinClause, using_columns),
    FOP_SEQ(3),
    FOP_KW(" USING ("),
    FOP_CHILD(JoinClause, using_columns),
    FOP_KW(")"),
    FOP_SEQ(7),
    FOP_CHILD(JoinClause, left),
    FOP_HARDLINE,
    FOP_ENUM_DISPLAY(JoinClause, join_type, fmt_join_clause_entries_1, 10),
    FOP_KW(" "),
    FOP_CHILD(JoinClause, right),
    FOP_IF_SET(JoinClause, on_expr),
    FOP_SEQ(3),
    FOP_HARDLINE,
    FOP_KW("ON "),
    FOP_CHILD(JoinClause, on_expr),
    FOP_IF_SET(JoinClause, using_columns),
    FOP_SEQ(3),
    FOP_KW(" USING ("),
    FOP_CHILD(JoinClause, using_columns),
    FOP_KW(")"),
};

static const SynqFmtOp fmt_join_prefix[] = {
    FOP_CHILD(JoinPrefix, source),
};

static const SynqFmtOp fmt_delete_stmt[] = {
    FOP_GROUP,
    FOP_SEQ(3),
    FOP_KW("DELETE"),
    FOP_CLAUSE(DeleteStmt, table, "FROM"),
    FOP_CLAUSE(DeleteStmt, where, "WHERE"),
};

static const SynqFmtOp fmt_set_clause[] = {
    FOP_SEQ(3),
    FOP_IF_SPAN_ELSE(SetClause, column),
    FOP_SPAN(SetClause, column),
    FOP_IF_SET(SetClause, columns),
    FOP_SEQ(3),
    FOP_KW("("),
    FOP_CHILD(SetClause, columns),
    FOP_KW(")"),
    FOP_KW(" = "),
    FOP_CHILD(SetClause, value),
};

static const SynqFmtOp fmt_update_stmt[] = {
    FOP_GROUP,
    FOP_SEQ(7),
    FOP_KW("UPDATE"),
    FOP_SWITCH(UpdateStmt, conflict_action, 5),
    FOP_CASE(SYNQ_CONFLICT_ACTION_ROLLBACK),
    FOP_KW(" OR ROLLBACK"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_ABORT),
    FOP_KW(" OR ABORT"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_FAIL),
    FOP_KW(" OR FAIL"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_IGNORE),
    FOP_KW(" OR IGNORE"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_REPLACE),
    FOP_KW(" OR REPLACE"),
    FOP_KW(" "),
    FOP_CHILD(UpdateStmt, table),
    FOP_CLAUSE(UpdateStmt, setlist, "SET"),
    FOP_CLAUSE(UpdateStmt, from_clause, "FROM"),
    FOP_CLAUSE(UpdateStmt, where, "WHERE"),
};

static const SynqFmtOp fmt_insert_stmt[] = {
    FOP_SEQ(5),
    FOP_IF_ENUM_ELSE(InsertStmt, conflict_action, SYNQ_CONFLICT_ACTION_REPLACE),
    FOP_KW("REPLACE"),
    FOP_SEQ(2),
    FOP_KW("INSERT"),
    FOP_SWITCH(InsertStmt, conflict_action, 4),
    FOP_CASE(SYNQ_CONFLICT_ACTION_ROLLBACK),
    FOP_KW(" OR ROLLBACK"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_ABORT),
    FOP_KW(" OR ABORT"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_FAIL),
    FOP_KW(" OR FAIL"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_IGNORE),
    FOP_KW(" OR IGNORE"),
    FOP_KW(" INTO "),
    FOP_CHILD(InsertStmt, table),
    FOP_IF_SET(InsertStmt, columns),
    FOP_SEQ(3),
    FOP_KW(" ("),
    FOP_CHILD(InsertStmt, columns),
    FOP_KW(")"),
    FOP_IF_SET(InsertStmt, source),
    FOP_SEQ(2),
    FOP_HARDLINE,
    FOP_CHILD(InsertStmt, source),
};

static const SynqFmtOp fmt_qualified_name[] = {
    FOP_SEQ(2),
    FOP_IF_SPAN(QualifiedName, schema),
    FOP_SEQ(2),
    FOP_SPAN(QualifiedName, schema),
    FOP_KW("."),
    FOP_SPAN(QualifiedName, object_name),
};

static const SynqFmtEnumEntry fmt_drop_stmt_entries_1[] = {
    { SYNQ_DROP_OBJECT_TYPE_TABLE, "TABLE" },
    { SYNQ_DROP_OBJECT_TYPE_INDEX, "INDEX" },
    { SYNQ_DROP_OBJECT_TYPE_VIEW, "VIEW" },
    { SYNQ_DROP_OBJECT_TYPE_TRIGGER, "TRIGGER" },
};

static const SynqFmtOp fmt_drop_stmt[] = {
    FOP_SEQ(5),
    FOP_KW("DROP "),
    FOP_ENUM_DISPLAY(DropStmt, object_type, fmt_drop_stmt_entries_1, 4),
    FOP_IF_ENUM(DropStmt, if_exists, SYNQ_BOOL_TRUE),
    FOP_KW(" IF EXISTS"),
    FOP_KW(" "),
    FOP_CHILD(DropStmt, target),
};

static const SynqFmtOp fmt_alter_table_stmt[] = {
    FOP_SEQ(3),
    FOP_KW("ALTER TABLE "),
    FOP_IF_SET(AlterTableStmt, target),
    FOP_SEQ(2),
    FOP_CHILD(AlterTableStmt, target),
    FOP_KW(" "),
    FOP_SWITCH(AlterTableStmt, op, 4),
    FOP_CASE(SYNQ_ALTER_OP_RENAME_TABLE),
    FOP_SEQ(2),
    FOP_KW("RENAME TO "),
    FOP_SPAN(AlterTableStmt, new_name),
    FOP_CASE(SYNQ_ALTER_OP_RENAME_COLUMN),
    FOP_SEQ(4),
    FOP_KW("RENAME COLUMN "),
    FOP_SPAN(AlterTableStmt, old_name),
    FOP_KW(" TO "),
    FOP_SPAN(AlterTableStmt, new_name),
    FOP_CASE(SYNQ_ALTER_OP_DROP_COLUMN),
    FOP_SEQ(2),
    FOP_KW("DROP COLUMN "),
    FOP_SPAN(AlterTableStmt, old_name),
    FOP_CASE(SYNQ_ALTER_OP_ADD_COLUMN),
    FOP_SEQ(2),
    FOP_KW("ADD COLUMN "),
    FOP_SPAN(AlterTableStmt, old_name),
};

static const SynqFmtEnumEntry fmt_transaction_stmt_entries_1[] = {
    { SYNQ_TRANSACTION_TYPE_IMMEDIATE, " IMMEDIATE" },
    { SYNQ_TRANSACTION_TYPE_EXCLUSIVE, " EXCLUSIVE" },
};

static const SynqFmtOp fmt_transaction_stmt[] = {
    FOP_SWITCH(TransactionStmt, op, 3),
    FOP_CASE(SYNQ_TRANSACTION_OP_BEGIN),
    FOP_SEQ(2),
    FOP_KW("BEGIN"),
    FOP_ENUM_DISPLAY(TransactionStmt, trans_type, fmt_transaction_stmt_entries_1, 2),
    FOP_CASE(SYNQ_TRANSACTION_OP_COMMIT),
    FOP_KW("COMMIT"),
    FOP_CASE(SYNQ_TRANSACTION_OP_ROLLBACK),
    FOP_KW("ROLLBACK"),
};

static const SynqFmtOp fmt_savepoint_stmt[] = {
    FOP_SWITCH(SavepointStmt, op, 3),
    FOP_CASE(SYNQ_SAVEPOINT_OP_SAVEPOINT),
    FOP_SEQ(2),
    FOP_KW("SAVEPOINT "),
    FOP_SPAN(SavepointStmt, savepoint_name),
    FOP_CASE(SYNQ_SAVEPOINT_OP_RELEASE),
    FOP_SEQ(2),
    FOP_KW("RELEASE SAVEPOINT "),
    FOP_SPAN(SavepointStmt, savepoint_name),
    FOP_CASE(SYNQ_SAVEPOINT_OP_ROLLBACK_TO),
    FOP_SEQ(2),
    FOP_KW("ROLLBACK TO SAVEPOINT "),
    FOP_SPAN(SavepointStmt, savepoint_name),
};

static const SynqFmtOp fmt_pragma_stmt[] = {
    FOP_SEQ(4),
    FOP_KW("PRAGMA "),
    FOP_IF_SPAN(PragmaStmt, schema),
    FOP_SEQ(2),
    FOP_SPAN(PragmaStmt, schema),
    FOP_KW("."),
    FOP_SPAN(PragmaStmt, pragma_name),
    FOP_SWITCH(PragmaStmt, pragma_form, 2),
    FOP_CASE(SYNQ_PRAGMA_FORM_EQ),
    FOP_SEQ(2),
    FOP_KW(" = "),
    FOP_SPAN(PragmaStmt, value),
    FOP_CASE(SYNQ_PRAGMA_FORM_CALL),
    FOP_SEQ(3),
    FOP_KW("("),
    FOP_SPAN(PragmaStmt, value),
    FOP_KW(")"),
};

static const SynqFmtOp fmt_analyze_stmt[] = {
    FOP_SEQ(2),
    FOP_IF_ENUM_ELSE(AnalyzeStmt, kind, SYNQ_ANALYZE_KIND_REINDEX),
    FOP_KW("REINDEX"),
    FOP_KW("ANALYZE"),
    FOP_IF_SPAN_ELSE(AnalyzeStmt, schema),
    FOP_SEQ(4),
    FOP_KW(" "),
    FOP_SPAN(AnalyzeStmt, schema),
    FOP_KW("."),
    FOP_SPAN(AnalyzeStmt, target_name),
    FOP_IF_SPAN(AnalyzeStmt, target_name),
    FOP_SEQ(2),
    FOP_KW(" "),
    FOP_SPAN(AnalyzeStmt, target_name),
};

static const SynqFmtOp fmt_attach_stmt[] = {
    FOP_SEQ(5),
    FOP_KW("ATTACH "),
    FOP_CHILD(AttachStmt, filename),
    FOP_KW(" AS "),
    FOP_CHILD(AttachStmt, db_name),
    FOP_IF_SET(AttachStmt, key),
    FOP_SEQ(2),
    FOP_KW(" KEY "),
    FOP_CHILD(AttachStmt, key),
};

static const SynqFmtOp fmt_detach_stmt[] = {
    FOP_SEQ(2),
    FOP_KW("DETACH "),
    FOP_CHILD(DetachStmt, db_name),
};

static const SynqFmtOp fmt_vacuum_stmt[] = {
    FOP_SEQ(3),
    FOP_KW("VACUUM"),
    FOP_IF_SPAN(VacuumStmt, schema),
    FOP_SEQ(2),
    FOP_KW(" "),
    FOP_SPAN(VacuumStmt, schema),
    FOP_IF_SET(VacuumStmt, into_expr),
    FOP_SEQ(2),
    FOP_KW(" INTO "),
    FOP_CHILD(VacuumStmt, into_expr),
};

static const SynqFmtOp fmt_explain_stmt[] = {
    FOP_SEQ(3),
    FOP_IF_ENUM_ELSE(ExplainStmt, explain_mode, SYNQ_EXPLAIN_MODE_QUERY_PLAN),
    FOP_KW("EXPLAIN QUERY PLAN"),
    FOP_KW("EXPLAIN"),
    FOP_HARDLINE,
    FOP_CHILD(ExplainStmt, stmt),
};

static const SynqFmtOp fmt_create_index_stmt[] = {
    FOP_GROUP,
    FOP_SEQ(13),
    FOP_KW("CREATE"),
    FOP_IF_ENUM(CreateIndexStmt, is_unique, SYNQ_BOOL_TRUE),
    FOP_KW(" UNIQUE"),
    FOP_KW(" INDEX"),
    FOP_IF_ENUM(CreateIndexStmt, if_not_exists, SYNQ_BOOL_TRUE),
    FOP_KW(" IF NOT EXISTS"),
    FOP_KW(" "),
    FOP_IF_SPAN(CreateIndexStmt, schema),
    FOP_SEQ(2),
    FOP_SPAN(CreateIndexStmt, schema),
    FOP_KW("."),
    FOP_SPAN(CreateIndexStmt, index_name),
    FOP_KW(" ON "),
    FOP_SPAN(CreateIndexStmt, table_name),
    FOP_KW(" ("),
    FOP_CHILD(CreateIndexStmt, columns),
    FOP_KW(")"),
    FOP_CLAUSE(CreateIndexStmt, where, "WHERE"),
};

static const SynqFmtOp fmt_create_view_stmt[] = {
    FOP_SEQ(11),
    FOP_KW("CREATE"),
    FOP_IF_ENUM(CreateViewStmt, is_temp, SYNQ_BOOL_TRUE),
    FOP_KW(" TEMP"),
    FOP_KW(" VIEW"),
    FOP_IF_ENUM(CreateViewStmt, if_not_exists, SYNQ_BOOL_TRUE),
    FOP_KW(" IF NOT EXISTS"),
    FOP_KW(" "),
    FOP_IF_SPAN(CreateViewStmt, schema),
    FOP_SEQ(2),
    FOP_SPAN(CreateViewStmt, schema),
    FOP_KW("."),
    FOP_SPAN(CreateViewStmt, view_name),
    FOP_IF_SET(CreateViewStmt, column_names),
    FOP_GROUP,
    FOP_SEQ(3),
    FOP_KW("("),
    FOP_CHILD(CreateViewStmt, column_names),
    FOP_KW(")"),
    FOP_KW(" AS"),
    FOP_HARDLINE,
    FOP_CHILD(CreateViewStmt, select),
};

static const SynqFmtOp fmt_foreign_key_clause[] = {
    FOP_SEQ(5),
    FOP_IF_SPAN(ForeignKeyClause, ref_table),
    FOP_SEQ(2),
    FOP_KW("REFERENCES "),
    FOP_SPAN(ForeignKeyClause, ref_table),
    FOP_IF_SET(ForeignKeyClause, ref_columns),
    FOP_SEQ(3),
    FOP_KW("("),
    FOP_CHILD(ForeignKeyClause, ref_columns),
    FOP_KW(")"),
    FOP_SWITCH(ForeignKeyClause, on_delete, 4),
    FOP_CASE(SYNQ_FOREIGN_KEY_ACTION_SET_NULL),
    FOP_KW(" ON DELETE SET NULL"),
    FOP_CASE(SYNQ_FOREIGN_KEY_ACTION_SET_DEFAULT),
    FOP_KW(" ON DELETE SET DEFAULT"),
    FOP_CASE(SYNQ_FOREIGN_KEY_ACTION_CASCADE),
    FOP_KW(" ON DELETE CASCADE"),
    FOP_CASE(SYNQ_FOREIGN_KEY_ACTION_RESTRICT),
    FOP_KW(" ON DELETE RESTRICT"),
    FOP_SWITCH(ForeignKeyClause, on_update, 4),
    FOP_CASE(SYNQ_FOREIGN_KEY_ACTION_SET_NULL),
    FOP_KW(" ON UPDATE SET NULL"),
    FOP_CASE(SYNQ_FOREIGN_KEY_ACTION_SET_DEFAULT),
    FOP_KW(" ON UPDATE SET DEFAULT"),
    FOP_CASE(SYNQ_FOREIGN_KEY_ACTION_CASCADE),
    FOP_KW(" ON UPDATE CASCADE"),
    FOP_CASE(SYNQ_FOREIGN_KEY_ACTION_RESTRICT),
    FOP_KW(" ON UPDATE RESTRICT"),
    FOP_IF_ENUM(ForeignKeyClause, is_deferred, SYNQ_BOOL_TRUE),
    FOP_KW("DEFERRABLE INITIALLY DEFERRED"),
};

static const SynqFmtOp fmt_column_constraint[] = {
    FOP_SEQ(2),
    FOP_IF_SPAN(ColumnConstraint, constraint_name),
    FOP_SEQ(3),
    FOP_KW("CONSTRAINT "),
    FOP_SPAN(ColumnConstraint, constraint_name),
    FOP_KW(" "),
    FOP_SWITCH(ColumnConstraint, kind, 9),
    FOP_CASE(SYNQ_COLUMN_CONSTRAINT_KIND_PRIMARY_KEY),
    FOP_SEQ(4),
    FOP_KW("PRIMARY KEY"),
    FOP_IF_ENUM(ColumnConstraint, sort_order, SYNQ_SORT_ORDER_DESC),
    FOP_KW(" DESC"),
    FOP_IF_ENUM(ColumnConstraint, is_autoincrement, SYNQ_BOOL_TRUE),
    FOP_KW(" AUTOINCREMENT"),
    FOP_SWITCH(ColumnConstraint, onconf, 5),
    FOP_CASE(SYNQ_CONFLICT_ACTION_ROLLBACK),
    FOP_KW(" ON CONFLICT ROLLBACK"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_ABORT),
    FOP_KW(" ON CONFLICT ABORT"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_FAIL),
    FOP_KW(" ON CONFLICT FAIL"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_IGNORE),
    FOP_KW(" ON CONFLICT IGNORE"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_REPLACE),
    FOP_KW(" ON CONFLICT REPLACE"),
    FOP_CASE(SYNQ_COLUMN_CONSTRAINT_KIND_NOT_NULL),
    FOP_SEQ(2),
    FOP_KW("NOT NULL"),
    FOP_SWITCH(ColumnConstraint, onconf, 5),
    FOP_CASE(SYNQ_CONFLICT_ACTION_ROLLBACK),
    FOP_KW(" ON CONFLICT ROLLBACK"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_ABORT),
    FOP_KW(" ON CONFLICT ABORT"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_FAIL),
    FOP_KW(" ON CONFLICT FAIL"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_IGNORE),
    FOP_KW(" ON CONFLICT IGNORE"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_REPLACE),
    FOP_KW(" ON CONFLICT REPLACE"),
    FOP_CASE(SYNQ_COLUMN_CONSTRAINT_KIND_UNIQUE),
    FOP_SEQ(2),
    FOP_KW("UNIQUE"),
    FOP_SWITCH(ColumnConstraint, onconf, 5),
    FOP_CASE(SYNQ_CONFLICT_ACTION_ROLLBACK),
    FOP_KW(" ON CONFLICT ROLLBACK"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_ABORT),
    FOP_KW(" ON CONFLICT ABORT"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_FAIL),
    FOP_KW(" ON CONFLICT FAIL"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_IGNORE),
    FOP_KW(" ON CONFLICT IGNORE"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_REPLACE),
    FOP_KW(" ON CONFLICT REPLACE"),
    FOP_CASE(SYNQ_COLUMN_CONSTRAINT_KIND_CHECK),
    FOP_SEQ(3),
    FOP_KW("CHECK("),
    FOP_CHILD(ColumnConstraint, check_expr),
    FOP_KW(")"),
    FOP_CASE(SYNQ_COLUMN_CONSTRAINT_KIND_DEFAULT),
    FOP_SEQ(2),
    FOP_KW("DEFAULT "),
    FOP_CHILD(ColumnConstraint, default_expr),
    FOP_CASE(SYNQ_COLUMN_CONSTRAINT_KIND_COLLATE),
    FOP_SEQ(2),
    FOP_KW("COLLATE "),
    FOP_SPAN(ColumnConstraint, collation_name),
    FOP_CASE(SYNQ_COLUMN_CONSTRAINT_KIND_REFERENCES),
    FOP_CHILD(ColumnConstraint, fk_clause),
    FOP_CASE(SYNQ_COLUMN_CONSTRAINT_KIND_GENERATED),
    FOP_SEQ(4),
    FOP_KW("AS ("),
    FOP_CHILD(ColumnConstraint, generated_expr),
    FOP_KW(")"),
    FOP_IF_ENUM(ColumnConstraint, generated_storage, SYNQ_GENERATED_COLUMN_STORAGE_STORED),
    FOP_KW(" STORED"),
    FOP_CASE(SYNQ_COLUMN_CONSTRAINT_KIND_NULL),
    FOP_KW("NULL"),
};

static const SynqFmtOp fmt_column_constraint_list[] = {
    FOP_FOR_EACH_SEP,
    FOP_CHILD_ITEM,
    FOP_KW(" "),
};

static const SynqFmtOp fmt_column_def[] = {
    FOP_SEQ(3),
    FOP_SPAN(ColumnDef, column_name),
    FOP_IF_SPAN(ColumnDef, type_name),
    FOP_SEQ(2),
    FOP_KW(" "),
    FOP_SPAN(ColumnDef, type_name),
    FOP_IF_SET(ColumnDef, constraints),
    FOP_SEQ(2),
    FOP_KW(" "),
    FOP_CHILD(ColumnDef, constraints),
};

static const SynqFmtOp fmt_column_def_list[] = {
    FOP_FOR_EACH_SEP,
    FOP_CHILD_ITEM,
    FOP_SEQ(2),
    FOP_KW(","),
    FOP_LINE,
};

static const SynqFmtOp fmt_table_constraint[] = {
    FOP_SEQ(2),
    FOP_IF_SPAN(TableConstraint, constraint_name),
    FOP_SEQ(3),
    FOP_KW("CONSTRAINT "),
    FOP_SPAN(TableConstraint, constraint_name),
    FOP_KW(" "),
    FOP_SWITCH(TableConstraint, kind, 4),
    FOP_CASE(SYNQ_TABLE_CONSTRAINT_KIND_PRIMARY_KEY),
    FOP_SEQ(4),
    FOP_KW("PRIMARY KEY("),
    FOP_CHILD(TableConstraint, columns),
    FOP_KW(")"),
    FOP_SWITCH(TableConstraint, onconf, 5),
    FOP_CASE(SYNQ_CONFLICT_ACTION_ROLLBACK),
    FOP_KW(" ON CONFLICT ROLLBACK"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_ABORT),
    FOP_KW(" ON CONFLICT ABORT"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_FAIL),
    FOP_KW(" ON CONFLICT FAIL"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_IGNORE),
    FOP_KW(" ON CONFLICT IGNORE"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_REPLACE),
    FOP_KW(" ON CONFLICT REPLACE"),
    FOP_CASE(SYNQ_TABLE_CONSTRAINT_KIND_UNIQUE),
    FOP_SEQ(4),
    FOP_KW("UNIQUE("),
    FOP_CHILD(TableConstraint, columns),
    FOP_KW(")"),
    FOP_SWITCH(TableConstraint, onconf, 5),
    FOP_CASE(SYNQ_CONFLICT_ACTION_ROLLBACK),
    FOP_KW(" ON CONFLICT ROLLBACK"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_ABORT),
    FOP_KW(" ON CONFLICT ABORT"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_FAIL),
    FOP_KW(" ON CONFLICT FAIL"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_IGNORE),
    FOP_KW(" ON CONFLICT IGNORE"),
    FOP_CASE(SYNQ_CONFLICT_ACTION_REPLACE),
    FOP_KW(" ON CONFLICT REPLACE"),
    FOP_CASE(SYNQ_TABLE_CONSTRAINT_KIND_CHECK),
    FOP_SEQ(3),
    FOP_KW("CHECK("),
    FOP_CHILD(TableConstraint, check_expr),
    FOP_KW(")"),
    FOP_CASE(SYNQ_TABLE_CONSTRAINT_KIND_FOREIGN_KEY),
    FOP_SEQ(4),
    FOP_KW("FOREIGN KEY("),
    FOP_CHILD(TableConstraint, columns),
    FOP_KW(") "),
    FOP_CHILD(TableConstraint, fk_clause),
};

static const SynqFmtOp fmt_table_constraint_list[] = {
    FOP_FOR_EACH_SEP,
    FOP_CHILD_ITEM,
    FOP_SEQ(2),
    FOP_KW(","),
    FOP_LINE,
};

static const SynqFmtOp fmt_create_table_stmt[] = {
    FOP_GROUP,
    FOP_SEQ(11),
    FOP_KW("CREATE"),
    FOP_IF_ENUM(CreateTableStmt, is_temp, SYNQ_BOOL_TRUE),
    FOP_KW(" TEMP"),
    FOP_KW(" TABLE"),
    FOP_IF_ENUM(CreateTableStmt, if_not_exists, SYNQ_BOOL_TRUE),
    FOP_KW(" IF NOT EXISTS"),
    FOP_KW(" "),
    FOP_IF_SPAN(CreateTableStmt, schema),
    FOP_SEQ(2),
    FOP_SPAN(CreateTableStmt, schema),
    FOP_KW("."),
    FOP_SPAN(CreateTableStmt, table_name),
    FOP_IF_SET(CreateTableStmt, columns),
    FOP_SEQ(4),
    FOP_KW("("),
    FOP_GROUP,
    FOP_NEST,
    FOP_SEQ(3),
    FOP_SOFTLINE,
    FOP_CHILD(CreateTableStmt, columns),
    FOP_IF_SET(CreateTableStmt, table_constraints),
    FOP_SEQ(3),
    FOP_KW(","),
    FOP_LINE,
    FOP_CHILD(CreateTableStmt, table_constraints),
    FOP_SOFTLINE,
    FOP_KW(")"),
    FOP_IF_SET(CreateTableStmt, as_select),
    FOP_SEQ(3),
    FOP_KW(" AS"),
    FOP_HARDLINE,
    FOP_CHILD(CreateTableStmt, as_select),
    FOP_IF_FLAG(CreateTableStmt, flags, 0x01),
    FOP_KW(" WITHOUT ROWID"),
    FOP_IF_FLAG(CreateTableStmt, flags, 0x02),
    FOP_KW(" STRICT"),
};

static const SynqFmtOp fmt_frame_bound[] = {
    FOP_SWITCH(FrameBound, bound_type, 5),
    FOP_CASE(SYNQ_FRAME_BOUND_TYPE_UNBOUNDED_PRECEDING),
    FOP_KW("UNBOUNDED PRECEDING"),
    FOP_CASE(SYNQ_FRAME_BOUND_TYPE_EXPR_PRECEDING),
    FOP_SEQ(2),
    FOP_CHILD(FrameBound, expr),
    FOP_KW(" PRECEDING"),
    FOP_CASE(SYNQ_FRAME_BOUND_TYPE_CURRENT_ROW),
    FOP_KW("CURRENT ROW"),
    FOP_CASE(SYNQ_FRAME_BOUND_TYPE_EXPR_FOLLOWING),
    FOP_SEQ(2),
    FOP_CHILD(FrameBound, expr),
    FOP_KW(" FOLLOWING"),
    FOP_CASE(SYNQ_FRAME_BOUND_TYPE_UNBOUNDED_FOLLOWING),
    FOP_KW("UNBOUNDED FOLLOWING"),
};

static const SynqFmtOp fmt_frame_spec[] = {
    FOP_SEQ(6),
    FOP_SWITCH(FrameSpec, frame_type, 3),
    FOP_CASE(SYNQ_FRAME_TYPE_RANGE),
    FOP_KW("RANGE"),
    FOP_CASE(SYNQ_FRAME_TYPE_ROWS),
    FOP_KW("ROWS"),
    FOP_CASE(SYNQ_FRAME_TYPE_GROUPS),
    FOP_KW("GROUPS"),
    FOP_KW(" BETWEEN "),
    FOP_CHILD(FrameSpec, start_bound),
    FOP_KW(" AND "),
    FOP_CHILD(FrameSpec, end_bound),
    FOP_SWITCH(FrameSpec, exclude, 4),
    FOP_CASE(SYNQ_FRAME_EXCLUDE_NO_OTHERS),
    FOP_KW(" EXCLUDE NO OTHERS"),
    FOP_CASE(SYNQ_FRAME_EXCLUDE_CURRENT_ROW),
    FOP_KW(" EXCLUDE CURRENT ROW"),
    FOP_CASE(SYNQ_FRAME_EXCLUDE_GROUP),
    FOP_KW(" EXCLUDE GROUP"),
    FOP_CASE(SYNQ_FRAME_EXCLUDE_TIES),
    FOP_KW(" EXCLUDE TIES"),
};

static const SynqFmtOp fmt_window_def[] = {
    FOP_IF_SPAN_ELSE(WindowDef, base_window_name),
    FOP_SPAN(WindowDef, base_window_name),
    FOP_SEQ(5),
    FOP_KW("("),
    FOP_IF_SET(WindowDef, partition_by),
    FOP_SEQ(2),
    FOP_KW("PARTITION BY "),
    FOP_CHILD(WindowDef, partition_by),
    FOP_IF_SET(WindowDef, orderby),
    FOP_SEQ(3),
    FOP_IF_SET(WindowDef, partition_by),
    FOP_KW(" "),
    FOP_KW("ORDER BY "),
    FOP_CHILD(WindowDef, orderby),
    FOP_IF_SET(WindowDef, frame),
    FOP_SEQ(2),
    FOP_IF_SET_ELSE(WindowDef, partition_by),
    FOP_KW(" "),
    FOP_IF_SET(WindowDef, orderby),
    FOP_KW(" "),
    FOP_CHILD(WindowDef, frame),
    FOP_KW(")"),
};

static const SynqFmtOp fmt_named_window_def[] = {
    FOP_SEQ(3),
    FOP_SPAN(NamedWindowDef, window_name),
    FOP_KW(" AS "),
    FOP_CHILD(NamedWindowDef, window_def),
};

static const SynqFmtOp fmt_filter_over[] = {
    FOP_SEQ(3),
    FOP_IF_SET(FilterOver, filter_expr),
    FOP_SEQ(3),
    FOP_KW("FILTER (WHERE "),
    FOP_CHILD(FilterOver, filter_expr),
    FOP_KW(")"),
    FOP_IF_SET(FilterOver, over_def),
    FOP_SEQ(2),
    FOP_KW(" OVER "),
    FOP_CHILD(FilterOver, over_def),
    FOP_IF_SPAN(FilterOver, over_name),
    FOP_SEQ(2),
    FOP_KW(" OVER "),
    FOP_SPAN(FilterOver, over_name),
};

static const SynqFmtOp fmt_trigger_event[] = {
    FOP_SWITCH(TriggerEvent, event_type, 3),
    FOP_CASE(SYNQ_TRIGGER_EVENT_TYPE_DELETE),
    FOP_KW("DELETE"),
    FOP_CASE(SYNQ_TRIGGER_EVENT_TYPE_INSERT),
    FOP_KW("INSERT"),
    FOP_CASE(SYNQ_TRIGGER_EVENT_TYPE_UPDATE),
    FOP_SEQ(2),
    FOP_KW("UPDATE"),
    FOP_IF_SET(TriggerEvent, columns),
    FOP_SEQ(2),
    FOP_KW(" OF "),
    FOP_CHILD(TriggerEvent, columns),
};

static const SynqFmtOp fmt_trigger_cmd_list[] = {
    FOP_FOR_EACH_SEP,
    FOP_SEQ(2),
    FOP_CHILD_ITEM,
    FOP_KW(";"),
    FOP_HARDLINE,
};

static const SynqFmtOp fmt_create_trigger_stmt[] = {
    FOP_SEQ(19),
    FOP_KW("CREATE"),
    FOP_IF_ENUM(CreateTriggerStmt, is_temp, SYNQ_BOOL_TRUE),
    FOP_KW(" TEMP"),
    FOP_KW(" TRIGGER"),
    FOP_IF_ENUM(CreateTriggerStmt, if_not_exists, SYNQ_BOOL_TRUE),
    FOP_KW(" IF NOT EXISTS"),
    FOP_KW(" "),
    FOP_IF_SPAN(CreateTriggerStmt, schema),
    FOP_SEQ(2),
    FOP_SPAN(CreateTriggerStmt, schema),
    FOP_KW("."),
    FOP_SPAN(CreateTriggerStmt, trigger_name),
    FOP_KW(" "),
    FOP_SWITCH(CreateTriggerStmt, timing, 3),
    FOP_CASE(SYNQ_TRIGGER_TIMING_BEFORE),
    FOP_KW("BEFORE"),
    FOP_CASE(SYNQ_TRIGGER_TIMING_AFTER),
    FOP_KW("AFTER"),
    FOP_CASE(SYNQ_TRIGGER_TIMING_INSTEAD_OF),
    FOP_KW("INSTEAD OF"),
    FOP_KW(" "),
    FOP_CHILD(CreateTriggerStmt, event),
    FOP_KW(" ON "),
    FOP_CHILD(CreateTriggerStmt, table),
    FOP_IF_SET(CreateTriggerStmt, when_expr),
    FOP_SEQ(3),
    FOP_HARDLINE,
    FOP_KW("WHEN "),
    FOP_CHILD(CreateTriggerStmt, when_expr),
    FOP_HARDLINE,
    FOP_KW("BEGIN"),
    FOP_IF_SET(CreateTriggerStmt, body),
    FOP_NEST,
    FOP_SEQ(2),
    FOP_HARDLINE,
    FOP_CHILD(CreateTriggerStmt, body),
    FOP_HARDLINE,
    FOP_KW("END"),
};

static const SynqFmtOp fmt_create_virtual_table_stmt[] = {
    FOP_SEQ(8),
    FOP_KW("CREATE VIRTUAL TABLE"),
    FOP_IF_ENUM(CreateVirtualTableStmt, if_not_exists, SYNQ_BOOL_TRUE),
    FOP_KW(" IF NOT EXISTS"),
    FOP_KW(" "),
    FOP_IF_SPAN(CreateVirtualTableStmt, schema),
    FOP_SEQ(2),
    FOP_SPAN(CreateVirtualTableStmt, schema),
    FOP_KW("."),
    FOP_SPAN(CreateVirtualTableStmt, table_name),
    FOP_KW(" USING "),
    FOP_SPAN(CreateVirtualTableStmt, module_name),
    FOP_IF_SPAN(CreateVirtualTableStmt, module_args),
    FOP_SEQ(3),
    FOP_KW("("),
    FOP_SPAN(CreateVirtualTableStmt, module_args),
    FOP_KW(")"),
};

// ============ Recipe Table ============

const SynqFmtOp *synq_fmt_recipes[SYNQ_NODE_COUNT] = {
    [SYNQ_NODE_BINARY_EXPR] = fmt_binary_expr,
    [SYNQ_NODE_UNARY_EXPR] = fmt_unary_expr,
    [SYNQ_NODE_LITERAL] = fmt_literal,
    [SYNQ_NODE_EXPR_LIST] = synq_fmt_default_comma_list,
    [SYNQ_NODE_RESULT_COLUMN] = fmt_result_column,
    [SYNQ_NODE_RESULT_COLUMN_LIST] = synq_fmt_default_comma_list,
    [SYNQ_NODE_SELECT_STMT] = fmt_select_stmt,
    [SYNQ_NODE_ORDERING_TERM] = fmt_ordering_term,
    [SYNQ_NODE_ORDER_BY_LIST] = synq_fmt_default_comma_list,
    [SYNQ_NODE_LIMIT_CLAUSE] = fmt_limit_clause,
    [SYNQ_NODE_COLUMN_REF] = fmt_column_ref,
    [SYNQ_NODE_FUNCTION_CALL] = fmt_function_call,
    [SYNQ_NODE_IS_EXPR] = fmt_is_expr,
    [SYNQ_NODE_BETWEEN_EXPR] = fmt_between_expr,
    [SYNQ_NODE_LIKE_EXPR] = fmt_like_expr,
    [SYNQ_NODE_CASE_EXPR] = fmt_case_expr,
    [SYNQ_NODE_CASE_WHEN] = fmt_case_when,
    [SYNQ_NODE_CASE_WHEN_LIST] = fmt_case_when_list,
    [SYNQ_NODE_COMPOUND_SELECT] = fmt_compound_select,
    [SYNQ_NODE_SUBQUERY_EXPR] = fmt_subquery_expr,
    [SYNQ_NODE_EXISTS_EXPR] = fmt_exists_expr,
    [SYNQ_NODE_IN_EXPR] = fmt_in_expr,
    [SYNQ_NODE_VARIABLE] = fmt_variable,
    [SYNQ_NODE_COLLATE_EXPR] = fmt_collate_expr,
    [SYNQ_NODE_CAST_EXPR] = fmt_cast_expr,
    [SYNQ_NODE_VALUES_ROW_LIST] = fmt_values_row_list,
    [SYNQ_NODE_VALUES_CLAUSE] = fmt_values_clause,
    [SYNQ_NODE_CTE_DEFINITION] = fmt_cte_definition,
    [SYNQ_NODE_CTE_LIST] = synq_fmt_default_comma_list,
    [SYNQ_NODE_WITH_CLAUSE] = fmt_with_clause,
    [SYNQ_NODE_AGGREGATE_FUNCTION_CALL] = fmt_aggregate_function_call,
    [SYNQ_NODE_RAISE_EXPR] = fmt_raise_expr,
    [SYNQ_NODE_TABLE_REF] = fmt_table_ref,
    [SYNQ_NODE_SUBQUERY_TABLE_SOURCE] = fmt_subquery_table_source,
    [SYNQ_NODE_JOIN_CLAUSE] = fmt_join_clause,
    [SYNQ_NODE_JOIN_PREFIX] = fmt_join_prefix,
    [SYNQ_NODE_DELETE_STMT] = fmt_delete_stmt,
    [SYNQ_NODE_SET_CLAUSE] = fmt_set_clause,
    [SYNQ_NODE_SET_CLAUSE_LIST] = synq_fmt_default_comma_list,
    [SYNQ_NODE_UPDATE_STMT] = fmt_update_stmt,
    [SYNQ_NODE_INSERT_STMT] = fmt_insert_stmt,
    [SYNQ_NODE_QUALIFIED_NAME] = fmt_qualified_name,
    [SYNQ_NODE_DROP_STMT] = fmt_drop_stmt,
    [SYNQ_NODE_ALTER_TABLE_STMT] = fmt_alter_table_stmt,
    [SYNQ_NODE_TRANSACTION_STMT] = fmt_transaction_stmt,
    [SYNQ_NODE_SAVEPOINT_STMT] = fmt_savepoint_stmt,
    [SYNQ_NODE_PRAGMA_STMT] = fmt_pragma_stmt,
    [SYNQ_NODE_ANALYZE_STMT] = fmt_analyze_stmt,
    [SYNQ_NODE_ATTACH_STMT] = fmt_attach_stmt,
    [SYNQ_NODE_DETACH_STMT] = fmt_detach_stmt,
    [SYNQ_NODE_VACUUM_STMT] = fmt_vacuum_stmt,
    [SYNQ_NODE_EXPLAIN_STMT] = fmt_explain_stmt,
    [SYNQ_NODE_CREATE_INDEX_STMT] = fmt_create_index_stmt,
    [SYNQ_NODE_CREATE_VIEW_STMT] = fmt_create_view_stmt,
    [SYNQ_NODE_FOREIGN_KEY_CLAUSE] = fmt_foreign_key_clause,
    [SYNQ_NODE_COLUMN_CONSTRAINT] = fmt_column_constraint,
    [SYNQ_NODE_COLUMN_CONSTRAINT_LIST] = fmt_column_constraint_list,
    [SYNQ_NODE_COLUMN_DEF] = fmt_column_def,
    [SYNQ_NODE_COLUMN_DEF_LIST] = fmt_column_def_list,
    [SYNQ_NODE_TABLE_CONSTRAINT] = fmt_table_constraint,
    [SYNQ_NODE_TABLE_CONSTRAINT_LIST] = fmt_table_constraint_list,
    [SYNQ_NODE_CREATE_TABLE_STMT] = fmt_create_table_stmt,
    [SYNQ_NODE_FRAME_BOUND] = fmt_frame_bound,
    [SYNQ_NODE_FRAME_SPEC] = fmt_frame_spec,
    [SYNQ_NODE_WINDOW_DEF] = fmt_window_def,
    [SYNQ_NODE_WINDOW_DEF_LIST] = synq_fmt_default_comma_list,
    [SYNQ_NODE_NAMED_WINDOW_DEF] = fmt_named_window_def,
    [SYNQ_NODE_NAMED_WINDOW_DEF_LIST] = synq_fmt_default_comma_list,
    [SYNQ_NODE_FILTER_OVER] = fmt_filter_over,
    [SYNQ_NODE_TRIGGER_EVENT] = fmt_trigger_event,
    [SYNQ_NODE_TRIGGER_CMD_LIST] = fmt_trigger_cmd_list,
    [SYNQ_NODE_CREATE_TRIGGER_STMT] = fmt_create_trigger_stmt,
    [SYNQ_NODE_CREATE_VIRTUAL_TABLE_STMT] = fmt_create_virtual_table_stmt,
};
