# Copyright 2025 The syntaqlite Authors. All rights reserved.
# Licensed under the Apache License, Version 2.0.
#
# @generated by syntaqlite-buildtools — DO NOT EDIT

from enum import IntEnum, IntFlag


class NodeTag(IntEnum):
    """AST node type tag."""

    NULL = 0
    AGGREGATE_FUNCTION_CALL = 1
    ORDERED_SET_FUNCTION_CALL = 2
    CAST_EXPR = 3
    COLUMN_REF = 4
    COMPOUND_SELECT = 5
    SUBQUERY_EXPR = 6
    EXISTS_EXPR = 7
    IN_EXPR = 8
    IS_EXPR = 9
    BETWEEN_EXPR = 10
    LIKE_EXPR = 11
    CASE_EXPR = 12
    CASE_WHEN = 13
    CASE_WHEN_LIST = 14
    FOREIGN_KEY_OPTION = 15
    FOREIGN_KEY_OPTION_LIST = 16
    FOREIGN_KEY_CLAUSE = 17
    COLUMN_CONSTRAINT = 18
    CONSTRAINT_NAME_DECLARATION = 19
    COLUMN_CONSTRAINT_LIST = 20
    COLUMN_DEF = 21
    COLUMN_DEF_LIST = 22
    TABLE_CONSTRAINT = 23
    TABLE_CONSTRAINT_GROUP = 24
    TABLE_CONSTRAINT_LIST = 25
    CREATE_TABLE_STMT = 26
    CTE_DEFINITION = 27
    CTE_LIST = 28
    WITH_CLAUSE = 29
    UPSERT_CLAUSE = 30
    UPSERT_CLAUSE_LIST = 31
    DELETE_STMT = 32
    SET_CLAUSE = 33
    SET_CLAUSE_LIST = 34
    UPDATE_STMT = 35
    INSERT_STMT = 36
    BINARY_EXPR = 37
    UNARY_EXPR = 38
    LITERAL = 39
    PAREN_EXPR = 40
    IDENT_NAME = 41
    ERROR = 42
    ROW_VALUE = 43
    EXPR_LIST = 44
    FUNCTION_CALL = 45
    VARIABLE = 46
    COLLATE_EXPR = 47
    RAISE_EXPR = 48
    QUALIFIED_NAME = 49
    DROP_STMT = 50
    ALTER_TABLE_STMT = 51
    TRANSACTION_STMT = 52
    SAVEPOINT_STMT = 53
    RESULT_COLUMN = 54
    RESULT_COLUMN_LIST = 55
    SELECT_STMT = 56
    ORDERING_TERM = 57
    ORDER_BY_LIST = 58
    LIMIT_CLAUSE = 59
    JOIN_MODIFIER = 60
    JOIN_MODIFIER_LIST = 61
    TABLE_REF = 62
    SUBQUERY_TABLE_SOURCE = 63
    PAREN_TABLE_SOURCE = 64
    JOIN_CLAUSE = 65
    JOIN_PREFIX = 66
    TRIGGER_EVENT = 67
    TRIGGER_CMD_LIST = 68
    CREATE_TRIGGER_STMT = 69
    CREATE_VIRTUAL_TABLE_STMT = 70
    PRAGMA_STMT = 71
    ANALYZE_OR_REINDEX_STMT = 72
    ATTACH_STMT = 73
    DETACH_STMT = 74
    VACUUM_STMT = 75
    EXPLAIN_STMT = 76
    CREATE_INDEX_STMT = 77
    CREATE_VIEW_STMT = 78
    VALUES_ROW_LIST = 79
    VALUES_CLAUSE = 80
    FRAME_BOUND = 81
    FRAME_SPEC = 82
    WINDOW_DEF = 83
    WINDOW_DEF_LIST = 84
    NAMED_WINDOW_DEF = 85
    NAMED_WINDOW_DEF_LIST = 86
    FILTER_OVER = 87


class Bool(IntEnum):
    FALSE = 0
    TRUE = 1


class LiteralType(IntEnum):
    INTEGER = 0
    FLOAT = 1
    STRING = 2
    BLOB = 3
    NULL = 4
    CURRENT = 5
    QNUMBER = 6


class BinaryOp(IntEnum):
    PLUS = 0
    MINUS = 1
    STAR = 2
    SLASH = 3
    REM = 4
    LT = 5
    GT = 6
    LE = 7
    GE = 8
    EQ = 9
    NE = 10
    AND = 11
    OR = 12
    BIT_AND = 13
    BIT_OR = 14
    LSHIFT = 15
    RSHIFT = 16
    CONCAT = 17
    PTR = 18
    PTR2 = 19


class UnaryOp(IntEnum):
    MINUS = 0
    PLUS = 1
    BIT_NOT = 2
    NOT = 3


class CompoundOp(IntEnum):
    UNION = 0
    UNION_ALL = 1
    INTERSECT = 2
    EXCEPT = 3


class IsOp(IntEnum):
    IS = 0
    IS_NOT = 1
    IS_NULL = 2
    NOT_NULL = 3
    IS_NOT_DISTINCT = 4
    IS_DISTINCT = 5


class LikeKeyword(IntEnum):
    LIKE = 0
    GLOB = 1
    MATCH = 2
    REGEXP = 3


class ForeignKeyAction(IntEnum):
    UNSET = 0
    NO_ACTION = 1
    SET_NULL = 2
    SET_DEFAULT = 3
    CASCADE = 4
    RESTRICT = 5


class Deferrable(IntEnum):
    UNSET = 0
    NOT_DEFERRABLE = 1
    DEFERRABLE = 2


class InitialDeferMode(IntEnum):
    UNSET = 0
    DEFERRED = 1
    IMMEDIATE = 2


class GeneratedColumnStorage(IntEnum):
    VIRTUAL = 0
    STORED = 1


class ColumnConstraintType(IntEnum):
    DEFAULT = 0
    NOT_NULL = 1
    PRIMARY_KEY = 2
    UNIQUE = 3
    CHECK = 4
    REFERENCES = 5
    COLLATE = 6
    GENERATED = 7
    NULL = 8
    DEFERRABLE = 9


class TableConstraintType(IntEnum):
    PRIMARY_KEY = 0
    UNIQUE = 1
    CHECK = 2
    FOREIGN_KEY = 3


class ForeignKeyOptionKind(IntEnum):
    MATCH = 0
    ON_DELETE = 1
    ON_UPDATE = 2
    ON_INSERT = 3


class Materialized(IntEnum):
    DEFAULT = 0
    MATERIALIZED = 1
    NOT_MATERIALIZED = 2


class ConflictAction(IntEnum):
    DEFAULT = 0
    ROLLBACK = 1
    ABORT = 2
    FAIL = 3
    IGNORE = 4
    REPLACE = 5


class UpsertAction(IntEnum):
    NOTHING = 0
    UPDATE = 1


class IndexHint(IntEnum):
    DEFAULT = 0
    NOT_INDEXED = 1
    INDEXED = 2


class RaiseType(IntEnum):
    IGNORE = 0
    ROLLBACK = 1
    ABORT = 2
    FAIL = 3


class DropObjectType(IntEnum):
    TABLE = 0
    INDEX = 1
    VIEW = 2
    TRIGGER = 3


class AlterOp(IntEnum):
    RENAME_TABLE = 0
    RENAME_COLUMN = 1
    DROP_COLUMN = 2
    ADD_COLUMN = 3


class TransactionType(IntEnum):
    DEFERRED = 0
    IMMEDIATE = 1
    EXCLUSIVE = 2


class TransactionOp(IntEnum):
    BEGIN = 0
    COMMIT = 1
    ROLLBACK = 2


class SavepointOp(IntEnum):
    SAVEPOINT = 0
    RELEASE = 1
    ROLLBACK_TO = 2


class SortOrder(IntEnum):
    ASC = 0
    DESC = 1


class NullsOrder(IntEnum):
    NONE = 0
    FIRST = 1
    LAST = 2


class JoinType(IntEnum):
    COMMA = 0
    INNER = 1
    LEFT = 2
    RIGHT = 3
    FULL = 4
    CROSS = 5
    NATURAL_INNER = 6
    NATURAL_LEFT = 7
    NATURAL_RIGHT = 8
    NATURAL_FULL = 9
    NATURAL_CROSS = 10


class JoinModifierKind(IntEnum):
    NATURAL = 0
    LEFT = 1
    OUTER = 2
    RIGHT = 3
    FULL = 4
    INNER = 5
    CROSS = 6


class TriggerTiming(IntEnum):
    BEFORE = 0
    AFTER = 1
    INSTEAD_OF = 2


class TriggerEventType(IntEnum):
    DELETE = 0
    INSERT = 1
    UPDATE = 2


class ExplainMode(IntEnum):
    EXPLAIN = 0
    QUERY_PLAN = 1


class PragmaForm(IntEnum):
    BARE = 0
    EQ = 1
    CALL = 2


class AnalyzeOrReindexOp(IntEnum):
    ANALYZE = 0
    REINDEX = 1


class FrameType(IntEnum):
    NONE = 0
    RANGE = 1
    ROWS = 2
    GROUPS = 3


class FrameBoundType(IntEnum):
    UNBOUNDED_PRECEDING = 0
    EXPR_PRECEDING = 1
    CURRENT_ROW = 2
    EXPR_FOLLOWING = 3
    UNBOUNDED_FOLLOWING = 4


class FrameExclude(IntEnum):
    NONE = 0
    NO_OTHERS = 1
    CURRENT_ROW = 2
    GROUP = 3
    TIES = 4


class AggregateFunctionCallFlags(IntFlag):
    DISTINCT = 1
    ALL = 4


class CreateTableStmtFlags(IntFlag):
    WITHOUT_ROWID = 1
    STRICT = 2


class FunctionCallFlags(IntFlag):
    DISTINCT = 1
    STAR = 2
    ALL = 4


class ResultColumnFlags(IntFlag):
    STAR = 1


class SelectStmtFlags(IntFlag):
    DISTINCT = 1
    ALL = 4


