// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.
//
// @generated by syntaqlite-buildtools — DO NOT EDIT

//! Static catalog of `SQLite` built-in relations with version/cflag availability.

use crate::dialect::{
    AvailabilityRule, BuiltinRelationEntry, BuiltinRelationInfo, CflagPolarity, SqliteVersion,
};

use AvailabilityRule as A;
use BuiltinRelationEntry as R;
use BuiltinRelationInfo as I;
use CflagPolarity::{Enable as E, Omit as O};
use SqliteVersion as V;

/// All 4 always-present `SQLite` built-in relations.
#[rustfmt::skip]
pub(crate) static SQLITE_RELATIONS: &[BuiltinRelationEntry<'static>] = &[
    R { info: I { name: "sqlite_master", columns: &["type", "name", "tbl_name", "rootpage", "sql"], without_rowid: false }, availability: &[A { since: V::V3_12, until: None, cflag_index: u32::MAX, cflag_polarity: E }] },
    R { info: I { name: "sqlite_schema", columns: &["type", "name", "tbl_name", "rootpage", "sql"], without_rowid: false }, availability: &[A { since: V::V3_33, until: None, cflag_index: u32::MAX, cflag_polarity: E }] },
    R { info: I { name: "sqlite_temp_master", columns: &["type", "name", "tbl_name", "rootpage", "sql"], without_rowid: false }, availability: &[A { since: V::V3_12, until: None, cflag_index: 14, cflag_polarity: O }] },
    R { info: I { name: "sqlite_temp_schema", columns: &["type", "name", "tbl_name", "rootpage", "sql"], without_rowid: false }, availability: &[A { since: V::V3_33, until: None, cflag_index: 14, cflag_polarity: O }] },
];
