// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

//! Generates `cflags.rs` files for the `SqliteFlag` and `SqliteSyntaxFlag` enums.
//!
//! Both flag enums are generated from [`super::cflag_registry::CFLAG_REGISTRY`]:
//!
//! - `SqliteFlag` (42 variants) → `syntaqlite/src/sqlite/cflags.rs`
//! - `SqliteSyntaxFlag` (22 parser-only variants) → `syntaqlite-syntax/src/sqlite/cflags.rs`
//!
//! Each enum is self-describing: variants carry their own name, categories,
//! and `from_name` lookup via `impl` methods backed by internal `const` arrays.

use std::collections::HashMap;
use std::fmt::Write as _;

use super::cflag_registry::{CFLAG_REGISTRY, PARSER_CFLAG_COUNT, cflag_index};
use super::pascal_case;

// ── Cflag metadata ────────────────────────────────────────────────────────────

#[derive(Debug, serde::Deserialize)]
struct MetadataFile {
    cflags: Vec<MetadataEntry>,
}

#[derive(Debug, serde::Deserialize)]
struct MetadataEntry {
    name: String,
    since: String,
    categories: Vec<String>,
}

/// Codegen metadata for one stable cflag registry entry.
#[derive(Debug)]
pub(crate) struct CflagMetadata {
    min_version: u32,
    categories: Vec<String>,
}

impl CflagMetadata {
    fn has_category(&self, category: &str) -> bool {
        self.categories.iter().any(|item| item == category)
    }
}

/// Load and validate all metadata from `version_cflags.json`.
///
/// # Errors
///
/// Returns an error if the file is unreadable or invalid, its names differ from
/// `CFLAG_REGISTRY`, or its parser categories disagree with the compact parser
/// index prefix.
pub(crate) fn load_cflag_metadata(path: &str) -> Result<HashMap<String, CflagMetadata>, String> {
    let content = std::fs::read_to_string(path).map_err(|e| format!("reading {path}: {e}"))?;
    let file: MetadataFile =
        serde_json::from_str(&content).map_err(|e| format!("parsing {path}: {e}"))?;
    let mut metadata = HashMap::new();
    for entry in file.cflags {
        if cflag_index(&entry.name).is_none() {
            return Err(format!(
                "{path}: metadata contains unknown cflag {}",
                entry.name
            ));
        }
        let name = entry.name;
        let value = CflagMetadata {
            min_version: parse_since(&entry.since),
            categories: entry.categories,
        };
        if metadata.insert(name.clone(), value).is_some() {
            return Err(format!("{path}: duplicate cflag metadata for {name}"));
        }
    }

    for &(name, index) in CFLAG_REGISTRY {
        let entry = metadata
            .get(name)
            .ok_or_else(|| format!("{path}: missing cflag metadata for {name}"))?;
        let expected_parser = index < PARSER_CFLAG_COUNT;
        if entry.has_category("parser") != expected_parser {
            return Err(format!(
                "{path}: parser category for {name} disagrees with stable index {index}"
            ));
        }
    }

    Ok(metadata)
}

fn parse_since(s: &str) -> u32 {
    if s == "0" {
        return 0;
    }
    let parts: Vec<u32> = s.split('.').filter_map(|p| p.parse().ok()).collect();
    match parts.as_slice() {
        [major, minor, patch] => major * 1_000_000 + minor * 1_000 + patch,
        _ => 0,
    }
}

// ── Version helpers ───────────────────────────────────────────────────────────

/// Map a version integer (e.g. `3030001`) to a `SqliteVersion::V3_NN` expression.
///
/// `0` (unknown/predates tracking) maps to the oldest tracked version (`V3_12`).
/// Only the major+minor components are used; patch is ignored.
fn version_to_variant(v: u32) -> String {
    if v == 0 {
        return "SqliteVersion::V3_12".to_string();
    }
    let minor = (v / 1_000) % 1_000;
    format!("SqliteVersion::V3_{minor}")
}

// ── Flag variant name ─────────────────────────────────────────────────────────

/// Derive the Rust `PascalCase` variant name from a `SQLITE_*` flag name.
///
/// Strips the `"SQLITE_"` prefix and applies `pascal_case`, e.g.
/// `"SQLITE_OMIT_WINDOWFUNC"` → `"OmitWindowfunc"`.
fn variant_name(sqlite_name: &str) -> String {
    let suffix = sqlite_name.strip_prefix("SQLITE_").unwrap_or(sqlite_name);
    pascal_case(suffix)
}

// ── SqliteFlag codegen ────────────────────────────────────────────────────────

/// Generate `syntaqlite/src/sqlite/cflags.rs` containing the `SqliteFlag` enum.
///
/// All 42 flags from [`CFLAG_REGISTRY`] are emitted in index order with
/// self-describing `impl` methods: `name()`, `categories()`, `from_name()`, `all()`,
/// `min_version()` metadata sourced from `version_cflags.json`.
pub(crate) fn generate_sqlite_flag_rs(metadata: &HashMap<String, CflagMetadata>) -> String {
    let mut out = String::new();
    out.push_str("// Copyright 2025 The syntaqlite Authors. All rights reserved.\n");
    out.push_str("// Licensed under the Apache License, Version 2.0.\n");
    out.push_str("// @generated by syntaqlite-buildtools — DO NOT EDIT\n\n");
    out.push_str("//! Compile-time feature flags for the `SQLite` dialect.\n\n");

    out.push_str("use syntaqlite_syntax::util::{SqliteSyntaxFlag, SqliteVersion};\n\n");
    out.push_str("/// A compile-time feature flag for the `SQLite` dialect.\n");
    out.push_str("///\n");
    out.push_str("/// Pass a variant to [`crate::util::SqliteFlags::has`],\n");
    out.push_str(
        "/// [`crate::util::SqliteFlags::with`], or [`crate::util::SqliteFlags::without`].\n",
    );
    out.push_str("#[repr(u32)]\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub enum SqliteFlag {\n");
    for &(name, idx) in CFLAG_REGISTRY {
        let variant = variant_name(name);
        writeln!(out, "    /// `{name}`\n    {variant} = {idx},").expect("write to String");
    }
    out.push_str("}\n\n");

    out.push_str("impl SqliteFlag {\n");

    // ALL array
    out.push_str("    const ALL: &'static [Self] = &[\n");
    for &(name, _) in CFLAG_REGISTRY {
        writeln!(out, "        Self::{},", variant_name(name)).expect("write to String");
    }
    out.push_str("    ];\n\n");

    // NAMES array
    out.push_str("    const NAMES: &'static [&'static str] = &[\n");
    for &(name, _) in CFLAG_REGISTRY {
        writeln!(out, "        \"{name}\",").expect("write to String");
    }
    out.push_str("    ];\n\n");

    // CATEGORIES array
    out.push_str("    const CATEGORIES: &'static [&'static [&'static str]] = &[\n");
    for &(name, _) in CFLAG_REGISTRY {
        let entry = metadata.get(name).expect("validated cflag metadata");
        let cats_str: Vec<String> = entry
            .categories
            .iter()
            .map(|category| format!("\"{category}\""))
            .collect();
        writeln!(out, "        &[{}],", cats_str.join(", ")).expect("write to String");
    }
    out.push_str("    ];\n\n");

    out.push_str("    const MIN_VERSIONS: &'static [SqliteVersion] = &[\n");
    for &(name, _) in CFLAG_REGISTRY {
        let entry = metadata.get(name).expect("validated cflag metadata");
        let variant = version_to_variant(entry.min_version);
        writeln!(out, "        {variant}, // {name}").expect("write to String");
    }
    out.push_str("    ];\n\n");

    out.push_str(
        r#"    /// The canonical `SQLITE_*` flag name (e.g. `"SQLITE_OMIT_WINDOWFUNC"`).
    pub fn name(self) -> &'static str {
        Self::NAMES[self as usize]
    }

    /// Which concerns this flag affects (e.g. `"parser"`, `"functions"`, `"vtable"`).
    pub fn categories(self) -> &'static [&'static str] {
        Self::CATEGORIES[self as usize]
    }

    /// Look up a flag by its canonical `SQLITE_*` name.
    ///
    /// Returns `None` if `s` is not a known flag name.
    pub fn from_name(s: &str) -> Option<Self> {
        Self::ALL.iter().copied().find(|f| f.name() == s)
    }

    /// All known flags in stable index order.
    pub fn all() -> &'static [Self] {
        Self::ALL
    }

"#,
    );

    out.push_str(
        r"    /// The minimum `SQLite` version at which this flag is known to exist.
    pub fn min_version(self) -> SqliteVersion {
        Self::MIN_VERSIONS[self as usize]
    }

",
    );

    out.push_str(
        r"    /// The corresponding [`SqliteSyntaxFlag`], if this is a parser-level flag.
    pub(crate) fn as_syntax_flag(self) -> Option<SqliteSyntaxFlag> {
        match self {
",
    );
    // Emit one arm per parser-category flag; all others map to None.
    for &(name, _) in CFLAG_REGISTRY {
        if metadata
            .get(name)
            .expect("validated cflag metadata")
            .has_category("parser")
        {
            let variant = variant_name(name);
            writeln!(
                out,
                "            Self::{variant} => Some(SqliteSyntaxFlag::{variant}),"
            )
            .expect("write to String");
        }
    }
    out.push_str("            _ => None,\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

/// Write the `SqliteFlag` enum to `output_path`.
///
/// # Errors
///
/// Returns an error if writing fails.
pub(crate) fn write_sqlite_flag_rs(
    output_path: &str,
    metadata: &HashMap<String, CflagMetadata>,
) -> Result<(), String> {
    use std::fs;
    use std::path::Path;
    let content = generate_sqlite_flag_rs(metadata);
    let out = Path::new(output_path);
    if let Some(parent) = out.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("creating output directory: {e}"))?;
    }
    fs::write(out, content).map_err(|e| format!("writing {}: {e}", out.display()))?;
    eprintln!("wrote {output_path}");
    Ok(())
}

// ── SqliteSyntaxFlag codegen ──────────────────────────────────────────────────

/// Generate `syntaqlite-syntax/src/sqlite/cflags.rs` containing `SqliteSyntaxFlag`.
///
/// Only the 22 parser-category flags from [`CFLAG_REGISTRY`] are emitted,
/// in index order (discriminants 0–21 matching `SYNQ_CFLAG_IDX_*` in `cflags.h`).
pub(crate) fn generate_syntax_flag_rs(metadata: &HashMap<String, CflagMetadata>) -> String {
    let parser_flags: Vec<(&str, u32)> = CFLAG_REGISTRY
        .iter()
        .filter(|(name, _)| {
            metadata
                .get(*name)
                .expect("validated cflag metadata")
                .has_category("parser")
        })
        .copied()
        .collect();

    let mut out = String::new();
    out.push_str("// Copyright 2025 The syntaqlite Authors. All rights reserved.\n");
    out.push_str("// Licensed under the Apache License, Version 2.0.\n");
    out.push_str("// @generated by syntaqlite-buildtools — DO NOT EDIT\n\n");
    out.push_str("//! Parser-level compile-time flags for the `SQLite` dialect.\n\n");

    out.push_str("/// A parser-level compile-time feature flag for the `SQLite` dialect.\n");
    out.push_str("///\n");
    out.push_str("/// Each variant corresponds to a `SYNQ_CFLAG_IDX_*` constant in `cflags.h`.\n");
    out.push_str("/// The discriminant equals the C compact index (0–21).\n");
    out.push_str("///\n");
    out.push_str("/// Pass a variant to [`crate::util::SqliteSyntaxFlags::has`] or\n");
    out.push_str("/// [`crate::util::SqliteSyntaxFlags::with`].\n");
    out.push_str("///\n");
    out.push_str("/// For the full 42-flag set use `syntaqlite::util::SqliteFlag`.\n");
    out.push_str("#[repr(u32)]\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub enum SqliteSyntaxFlag {\n");
    for &(name, idx) in &parser_flags {
        let variant = variant_name(name);
        writeln!(out, "    /// `{name}`\n    {variant} = {idx},").expect("write to String");
    }
    out.push_str("}\n\n");

    out.push_str("impl SqliteSyntaxFlag {\n");

    // ALL
    out.push_str("    const ALL: &'static [Self] = &[\n");
    for &(name, _) in &parser_flags {
        writeln!(out, "        Self::{},", variant_name(name)).expect("write to String");
    }
    out.push_str("    ];\n\n");

    // NAMES
    out.push_str("    const NAMES: &'static [&'static str] = &[\n");
    for &(name, _) in &parser_flags {
        writeln!(out, "        \"{name}\",").expect("write to String");
    }
    out.push_str("    ];\n\n");

    out.push_str(
        r#"    /// The canonical `SQLITE_*` flag name (e.g. `"SQLITE_OMIT_WINDOWFUNC"`).
    pub fn name(self) -> &'static str {
        Self::NAMES[self as usize]
    }

    /// Look up a parser flag by its canonical `SQLITE_*` name.
    ///
    /// Returns `None` if `s` is not a known parser flag name.
    pub fn from_name(s: &str) -> Option<Self> {
        Self::ALL.iter().copied().find(|f| f.name() == s)
    }

}

"#,
    );
    out
}

/// Write the `SqliteSyntaxFlag` enum to `output_path`.
///
/// # Errors
///
/// Returns an error if writing fails.
pub(crate) fn write_syntax_flag_rs(
    output_path: &str,
    metadata: &HashMap<String, CflagMetadata>,
) -> Result<(), String> {
    use std::fs;
    use std::path::Path;
    let content = generate_syntax_flag_rs(metadata);
    let out = Path::new(output_path);
    if let Some(parent) = out.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("creating output directory: {e}"))?;
    }
    fs::write(out, content).map_err(|e| format!("writing {}: {e}", out.display()))?;
    eprintln!("wrote {output_path}");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sqlite_flag_categories_come_from_metadata() {
        let mut metadata: HashMap<String, CflagMetadata> = CFLAG_REGISTRY
            .iter()
            .map(|&(name, index)| {
                let categories = if index < PARSER_CFLAG_COUNT {
                    vec!["parser".to_string()]
                } else {
                    Vec::new()
                };
                (
                    name.to_string(),
                    CflagMetadata {
                        min_version: 0,
                        categories,
                    },
                )
            })
            .collect();
        metadata
            .get_mut("SQLITE_ENABLE_FTS3")
            .expect("registry contains FTS3")
            .categories = vec!["json-owned-category".to_string()];

        let generated = generate_sqlite_flag_rs(&metadata);
        let categories: Vec<&str> = generated
            .split("const CATEGORIES")
            .nth(1)
            .expect("generated categories")
            .split("];\n")
            .next()
            .expect("categories array")
            .lines()
            .filter(|line| line.trim_start().starts_with("&["))
            .collect();

        assert_eq!(categories[31].trim(), "&[\"json-owned-category\"],");
    }
}
