// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

//! Build script for `syntaqlite-syntax`.
//!
//! Compiles the C tokenizer and parser sources and links them into the crate.

use std::env;
use std::path::PathBuf;

#[expect(clippy::too_many_lines)]
fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let csrc = manifest_dir.join("csrc");
    let include_dir = manifest_dir.join("include");
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let target_env = env::var("CARGO_CFG_TARGET_ENV").unwrap_or_default();
    let sqlite_enabled = env::var("CARGO_FEATURE_SQLITE").is_ok();

    // ── Stage generated headers for the `embedded-sources` feature ──────
    //
    // `embedded_sources.rs` `include_str!`s a couple of headers that are
    // GENERATED by the codegen pipeline (not hand-written) — currently
    // `csrc/tokens.h` and `include/syntaqlite/cflags.h` — so that
    // downstream amalgamation consumers can resolve runtime `#include`s
    // without invoking the dialect codegen pipeline.  This is an
    // intentional circular dependency (embedded-sources depends on a
    // generated file) and is documented in `embedded_sources.rs`.
    //
    // Problem: `tools/run-bootstrap-test` deletes every generated file
    // from the manifest and then tries to build `syntaqlite-buildtools`.
    // With `include_str!` pointing at the source tree, that compile
    // fails before codegen ever runs.
    //
    // Fix: stage each generated header into `OUT_DIR` here, writing a
    // placeholder stub if the source copy has been deleted.
    // `embedded_sources.rs` `include_str!`s the staged copy.  Normal
    // builds copy the real file unchanged; the bootstrap test path
    // writes a stub that is superseded as soon as `tools/run-codegen`
    // regenerates the real file.  The stub is never used by any real
    // consumer — it only exists to satisfy the compile-time
    // `include_str!`.
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    stage_generated_header(
        &csrc.join("tokens.h"),
        &out_dir.join("embedded_tokens.h"),
        "csrc/tokens.h",
    );
    stage_generated_header(
        &include_dir.join("syntaqlite").join("cflags.h"),
        &out_dir.join("embedded_cflags.h"),
        "include/syntaqlite/cflags.h",
    );

    // Use clang-cl on MSVC targets — MSVC's C compiler lacks C11 features
    // we rely on (designated initializers in static const).
    if target_env == "msvc" && env::var("CC").is_err() {
        // SAFETY: build scripts are single-threaded; no other threads
        // are reading environment variables at this point.
        unsafe { env::set_var("CC", "clang-cl") };
    }

    // Expose include directory so downstream crates can find headers.
    println!("cargo:include={}", include_dir.display());

    if env::var("CARGO_FEATURE_NO_BUNDLED_PARSER").is_ok() {
        // Skip C compilation — caller links a pre-built library.
        return;
    }

    if env::var("CARGO_FEATURE_SQLITE_MINIMAL").is_err() {
        // No parser features active (e.g. only embedded-sources) — nothing to compile.
        return;
    }

    // ── Grammar-agnostic engine sources ─────────────────────────────────
    //
    // Always compiled: tokenizer.c and the parser runtime engine
    // (split across parser.c, parser_macros.c, parser_dump.c).
    let mut engine_build = cc::Build::new();
    engine_build
        .file(csrc.join("tokenizer.c"))
        .file(csrc.join("parser.c"))
        .file(csrc.join("parser_macros.c"))
        .file(csrc.join("parser_dump.c"))
        .file(csrc.join("token_wrapped.c"))
        .file(csrc.join("dialect_load.c"))
        .include(&manifest_dir) // for csrc/*.h internal headers
        .include(&include_dir); // for public syntaqlite/*.h headers
    if !sqlite_enabled {
        engine_build.define("SYNTAQLITE_OMIT_SQLITE_API", None);
    }
    if env::var("CARGO_FEATURE_FMT").is_ok() {
        engine_build.define("SYNTAQLITE_FMT", None);
    }
    if env::var("CARGO_FEATURE_VALIDATION").is_ok() {
        engine_build.define("SYNTAQLITE_VALIDATION", None);
    }
    if target_os == "emscripten" {
        engine_build.flag("-fPIC");
    }
    engine_build.compile("syntaqlite_engine");

    // ── SQLite grammar ───────────────────────────────────────────────────
    if sqlite_enabled {
        let sqlite_csrc = csrc.join("sqlite");
        let mut build = cc::Build::new();
        build
            .file(sqlite_csrc.join("dialect.c"))
            .file(sqlite_csrc.join("sqlite_parse.c"))
            .file(sqlite_csrc.join("sqlite_tokenize.c"))
            .file(sqlite_csrc.join("sqlite_keyword.c"))
            .include(&manifest_dir) // for csrc/sqlite/*.h internal headers
            .include(&include_dir) // for public syntaqlite*/*.h headers
            .flag_if_supported("-Wno-int-conversion")
            .flag_if_supported("-Wno-void-pointer-to-int-cast")
            .flag_if_supported("-Wno-unused-variable")
            .flag_if_supported("-Wno-unused-parameter")
            .flag_if_supported("-Wno-unused-value")
            .flag_if_supported("-Wno-comment")
            .flag_if_supported("-Wno-type-limits")
            .flag_if_supported("-Wno-old-style-declaration")
            .flag_if_supported("-Wno-implicit-fallthrough");
        if env::var("CARGO_FEATURE_FMT").is_ok() {
            build.define("SYNTAQLITE_FMT", None);
        }
        if env::var("CARGO_FEATURE_VALIDATION").is_ok() {
            build.define("SYNTAQLITE_VALIDATION", None);
        }
        if target_os == "emscripten" {
            build.flag("-fPIC");
        }

        // ── Version pinning ──────────────────────────────────────────────
        if env::var("CARGO_FEATURE_PIN_VERSION").is_ok() {
            let ver_str = env::var("SYNTAQLITE_SQLITE_VERSION").unwrap_or_else(|_| {
                panic!(
                    "pin-version feature requires SYNTAQLITE_SQLITE_VERSION env var \
                     (e.g. SYNTAQLITE_SQLITE_VERSION=3035000)"
                )
            });
            let _: i32 = ver_str.parse().unwrap_or_else(|_| {
                panic!(
                    "SYNTAQLITE_SQLITE_VERSION must be an integer (e.g. 3035000), got: {ver_str}"
                )
            });
            build.define("SYNTAQLITE_SQLITE_VERSION", ver_str.as_str());
        }

        // ── Cflag pinning ────────────────────────────────────────────────
        if env::var("CARGO_FEATURE_PIN_CFLAGS").is_ok() {
            let cflags_header = std::fs::read_to_string(include_dir.join("syntaqlite/cflags.h"))
                .expect("failed to read cflags.h from include/syntaqlite/");

            build.define("SYNTAQLITE_SQLITE_CFLAGS", None);

            for line in cflags_header.lines() {
                let Some(rest) = line.strip_prefix("#define SYNQ_CFLAG_IDX_") else {
                    continue;
                };
                let mut parts = rest.split_whitespace();
                let Some(raw_suffix) = parts.next() else {
                    continue;
                };
                if raw_suffix == "COUNT" {
                    continue;
                }
                let suffix = format!("SQLITE_{raw_suffix}");
                let env_key = format!("SYNTAQLITE_CFLAG_{suffix}");
                if env::var(&env_key).is_ok() {
                    build.define(&env_key, None);
                    println!("cargo:rerun-if-env-changed={env_key}");
                }
            }
        }

        build.compile("syntaqlite_sqlite");
    }

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=csrc");
    println!("cargo:rerun-if-changed=include");
    println!("cargo:rerun-if-env-changed=SYNTAQLITE_SQLITE_VERSION");
}

/// Copy a generated header into `OUT_DIR` so `embedded_sources.rs` can
/// `include_str!` it.  When the source file has been deleted (e.g. by
/// `tools/run-bootstrap-test`), write a placeholder stub instead — the
/// stub is never observed by real consumers, it only exists to satisfy
/// the compile-time `include_str!` until `tools/run-codegen` regenerates
/// the real file.  See the caller for full context.
fn stage_generated_header(source: &std::path::Path, staged: &std::path::Path, rel: &str) {
    if source.exists() {
        std::fs::copy(source, staged)
            .unwrap_or_else(|e| panic!("failed to stage {rel} into OUT_DIR: {e}"));
    } else {
        std::fs::write(
            staged,
            format!("/* Placeholder — real {rel} is generated by tools/run-codegen. */\n"),
        )
        .unwrap_or_else(|e| panic!("failed to write {rel} placeholder into OUT_DIR: {e}"));
    }
    println!("cargo:rerun-if-changed={}", source.display());
}
