// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

//! Embedded hand-written C sources and headers for use by `syntaqlite-buildtools`.
//!
//! This module is only available with the `embedded-sources` feature and is
//! intended solely for `syntaqlite-buildtools` amalgamation support. It embeds
//! the hand-written runtime C sources and public headers as string constants so
//! that the buildtools crate is self-contained when published to crates.io.
//!
//! None of these files are generated — they are all hand-written and live under
//! `syntaqlite-syntax/csrc/` and `syntaqlite-syntax/include/`.

/// Embedded `include/syntaqlite/` public runtime headers.
///
/// Keyed by filename (e.g. `"types.h"`).
pub const RUNTIME_HEADERS: &[(&str, &str)] = &[
    ("dialect.h", include_str!("../include/syntaqlite/dialect.h")),
    // NOTE: include/syntaqlite/cflags.h is generated by the codegen
    // pipeline (see tools/generated-files.txt).  We `include_str!` from
    // `OUT_DIR` rather than directly from the source tree: `build.rs`
    // stages a copy there (or writes a placeholder stub when the
    // source file has been deleted — e.g. by
    // `tools/run-bootstrap-test`).  Same rationale as `tokens.h` below.
    (
        "cflags.h",
        include_str!(concat!(env!("OUT_DIR"), "/embedded_cflags.h")),
    ),
    (
        "compiler.h",
        include_str!("../include/syntaqlite/compiler.h"),
    ),
    ("config.h", include_str!("../include/syntaqlite/config.h")),
    ("parser.h", include_str!("../include/syntaqlite/parser.h")),
    (
        "incremental.h",
        include_str!("../include/syntaqlite/incremental.h"),
    ),
    (
        "tokenizer.h",
        include_str!("../include/syntaqlite/tokenizer.h"),
    ),
    ("types.h", include_str!("../include/syntaqlite/types.h")),
];

/// Embedded `csrc/` runtime C sources and internal headers (top-level only).
///
/// Keyed by filename (e.g. `"parser.c"`).
pub const RUNTIME_CSRC: &[(&str, &str)] = &[
    (
        "dialect_dispatch.h",
        include_str!("../csrc/dialect_dispatch.h"),
    ),
    ("parser.c", include_str!("../csrc/parser.c")),
    ("parser_macros.c", include_str!("../csrc/parser_macros.c")),
    ("parser_spans.c", include_str!("../csrc/parser_spans.c")),
    ("parser_extents.c", include_str!("../csrc/parser_extents.c")),
    ("parser_dump.c", include_str!("../csrc/parser_dump.c")),
    (
        "parser_internal.h",
        include_str!("../csrc/parser_internal.h"),
    ),
    ("token_wrapped.c", include_str!("../csrc/token_wrapped.c")),
    ("token_wrapped.h", include_str!("../csrc/token_wrapped.h")),
    ("tokenizer.c", include_str!("../csrc/tokenizer.c")),
    ("util.h", include_str!("../csrc/util.h")),
    // NOTE: csrc/tokens.h is generated by the codegen pipeline, but we embed it
    // here so that `runtime-only` amalgamation (which skips dialect codegen) can
    // resolve the `#include "csrc/tokens.h"` in parser.c and token_wrapped.c.
    // The codegen pipeline keeps this file in sync via `tools/run-codegen`.
    //
    // We `include_str!` from `OUT_DIR` rather than directly from the source
    // tree: `build.rs` stages a copy there (or writes a placeholder stub
    // when the source file has been deleted — e.g. by
    // `tools/run-bootstrap-test`).  See the corresponding comment in
    // `syntaqlite-syntax/build.rs` for details.
    (
        "tokens.h",
        include_str!(concat!(env!("OUT_DIR"), "/embedded_tokens.h")),
    ),
];

/// Embedded `include/syntaqlite_dialect/` extension SPI headers.
///
/// Keyed by filename (e.g. `"arena.h"`).
pub const DIALECT_EXT_HEADERS: &[(&str, &str)] = &[
    (
        "arena.h",
        include_str!("../include/syntaqlite_dialect/arena.h"),
    ),
    (
        "ast_builder.h",
        include_str!("../include/syntaqlite_dialect/ast_builder.h"),
    ),
    (
        "dialect_abi.h",
        include_str!("../include/syntaqlite_dialect/dialect_abi.h"),
    ),
    (
        "dialect_macros.h",
        include_str!("../include/syntaqlite_dialect/dialect_macros.h"),
    ),
    (
        "dialect_types.h",
        include_str!("../include/syntaqlite_dialect/dialect_types.h"),
    ),
    (
        "extent_hooks.h",
        include_str!("../include/syntaqlite_dialect/extent_hooks.h"),
    ),
    (
        "sqlite_compat.h",
        include_str!("../include/syntaqlite_dialect/sqlite_compat.h"),
    ),
    ("vec.h", include_str!("../include/syntaqlite_dialect/vec.h")),
];
