/*
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
** Token definitions from SQLite's parse.y via Lemon.
** DO NOT EDIT - regenerate with: python3 python/tools/extract_sqlite.py
*/
#ifndef SYNQ_SRC_SQLITE_TOKENS_H
#define SYNQ_SRC_SQLITE_TOKENS_H

#define TK_INDEX                            1
#define TK_ALTER                            2
#define TK_EXPLAIN                          3
#define TK_ADD                              4
#define TK_QUERY                            5
#define TK_WINDOW                           6
#define TK_PLAN                             7
#define TK_OVER                             8
#define TK_BEGIN                            9
#define TK_FILTER                          10
#define TK_TRANSACTION                     11
#define TK_COLUMN                          12
#define TK_DEFERRED                        13
#define TK_AGG_FUNCTION                    14
#define TK_IMMEDIATE                       15
#define TK_AGG_COLUMN                      16
#define TK_EXCLUSIVE                       17
#define TK_TRUEFALSE                       18
#define TK_COMMIT                          19
#define TK_FUNCTION                        20
#define TK_END                             21
#define TK_UPLUS                           22
#define TK_ROLLBACK                        23
#define TK_UMINUS                          24
#define TK_SAVEPOINT                       25
#define TK_TRUTH                           26
#define TK_RELEASE                         27
#define TK_REGISTER                        28
#define TK_TO                              29
#define TK_VECTOR                          30
#define TK_TABLE                           31
#define TK_SELECT_COLUMN                   32
#define TK_CREATE                          33
#define TK_IF_NULL_ROW                     34
#define TK_IF                              35
#define TK_ASTERISK                        36
#define TK_NOT                             37
#define TK_SPAN                            38
#define TK_EXISTS                          39
#define TK_ERROR                           40
#define TK_TEMP                            41
#define TK_QNUMBER                         42
#define TK_AS                              43
#define TK_WITHOUT                         44
#define TK_ABORT                           45
#define TK_ACTION                          46
#define TK_AFTER                           47
#define TK_ANALYZE                         48
#define TK_ASC                             49
#define TK_ATTACH                          50
#define TK_BEFORE                          51
#define TK_BY                              52
#define TK_CASCADE                         53
#define TK_CAST                            54
#define TK_CONFLICT                        55
#define TK_DATABASE                        56
#define TK_DESC                            57
#define TK_DETACH                          58
#define TK_EACH                            59
#define TK_FAIL                            60
#define TK_OR                              61
#define TK_AND                             62
#define TK_IS                              63
#define TK_ISNOT                           64
#define TK_MATCH                           65
#define TK_LIKE_KW                         66
#define TK_BETWEEN                         67
#define TK_IN                              68
#define TK_ISNULL                          69
#define TK_NOTNULL                         70
#define TK_ESCAPE                          71
#define TK_COLUMNKW                        72
#define TK_DO                              73
#define TK_FOR                             74
#define TK_IGNORE                          75
#define TK_INITIALLY                       76
#define TK_INSTEAD                         77
#define TK_NO                              78
#define TK_KEY                             79
#define TK_OF                              80
#define TK_OFFSET                          81
#define TK_PRAGMA                          82
#define TK_RAISE                           83
#define TK_RECURSIVE                       84
#define TK_REPLACE                         85
#define TK_RESTRICT                        86
#define TK_ROW                             87
#define TK_ROWS                            88
#define TK_TRIGGER                         89
#define TK_VACUUM                          90
#define TK_VIEW                            91
#define TK_VIRTUAL                         92
#define TK_WITH                            93
#define TK_NULLS                           94
#define TK_FIRST                           95
#define TK_LAST                            96
#define TK_CURRENT                         97
#define TK_FOLLOWING                       98
#define TK_PARTITION                       99
#define TK_PRECEDING                      100
#define TK_RANGE                          101
#define TK_UNBOUNDED                      102
#define TK_EXCLUDE                        103
#define TK_GROUPS                         104
#define TK_OTHERS                         105
#define TK_TIES                           106
#define TK_GENERATED                      107
#define TK_ALWAYS                         108
#define TK_MATERIALIZED                   109
#define TK_REINDEX                        110
#define TK_RENAME                         111
#define TK_CTIME_KW                       112
#define TK_ANY                            113
#define TK_COLLATE                        114
#define TK_ON                             115
#define TK_INDEXED                        116
#define TK_JOIN_KW                        117
#define TK_CONSTRAINT                     118
#define TK_DEFAULT                        119
#define TK_NULL                           120
#define TK_PRIMARY                        121
#define TK_UNIQUE                         122
#define TK_CHECK                          123
#define TK_REFERENCES                     124
#define TK_AUTOINCR                       125
#define TK_INSERT                         126
#define TK_DELETE                         127
#define TK_UPDATE                         128
#define TK_SET                            129
#define TK_DEFERRABLE                     130
#define TK_FOREIGN                        131
#define TK_DROP                           132
#define TK_UNION                          133
#define TK_ALL                            134
#define TK_EXCEPT                         135
#define TK_INTERSECT                      136
#define TK_SELECT                         137
#define TK_VALUES                         138
#define TK_DISTINCT                       139
#define TK_FROM                           140
#define TK_JOIN                           141
#define TK_USING                          142
#define TK_ORDER                          143
#define TK_GROUP                          144
#define TK_HAVING                         145
#define TK_LIMIT                          146
#define TK_WHERE                          147
#define TK_RETURNING                      148
#define TK_INTO                           149
#define TK_NOTHING                        150
#define TK_CASE                           151
#define TK_WHEN                           152
#define TK_THEN                           153
#define TK_ELSE                           154
#define TK_NE                             155
#define TK_EQ                             156
#define TK_GT                             157
#define TK_LE                             158
#define TK_LT                             159
#define TK_GE                             160
#define TK_BITAND                         161
#define TK_BITOR                          162
#define TK_LSHIFT                         163
#define TK_RSHIFT                         164
#define TK_PLUS                           165
#define TK_MINUS                          166
#define TK_STAR                           167
#define TK_SLASH                          168
#define TK_REM                            169
#define TK_CONCAT                         170
#define TK_PTR                            171
#define TK_BITNOT                         172
#define TK_ID                             173
#define TK_LP                             174
#define TK_RP                             175
#define TK_COMMA                          176
#define TK_STRING                         177
#define TK_DOT                            178
#define TK_FLOAT                          179
#define TK_BLOB                           180
#define TK_INTEGER                        181
#define TK_VARIABLE                       182
#define TK_SEMI                           183
#define TK_SPACE                          184
#define TK_COMMENT                        185
#define TK_ILLEGAL                        186

#endif /* SYNQ_SRC_SQLITE_TOKENS_H */
